### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by LeonardoGentile** [dannyvankooten/browserpass#10]
Hello, I've tried this and after messing up with gpg keys and other stuff I've decided pass and browserpass is not for me. Could you provide instructions on how to completely uninstall what has been installed with install.sh?

Thanks

**Comment by dannyvankooten** [comment]
Hey @LeonardoGentile,

It really depends on which browser & OS you're using, but the following should do the trick for all OS'es, all browsers & site-wide or user specific installation. Please note that it's not really _that_ important to get rid of these files, they're just really small configuration files for your browser.

```
rm "/Library/Google/Chrome/NativeMessagingHosts/com.dannyvankooten.browserpass.json"
rm "/Library/Application Support/Chromium/NativeMessagingHosts/com.dannyvankooten.browserpass.json"
rm "/Library/Application Support/Mozilla/NativeMessagingHosts/com.dannyvankooten.browserpass.json"
rm "$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts/com.dannyvankooten.browserpass.json"
rm "$HOME/Library/Application Support/Chromium/NativeMessagingHosts/com.dannyvankooten.browserpass.json"
rm "$HOME/Library/Application Support/Mozilla/NativeMessagingHosts/com.dannyvankooten.browserpass.json"
rm "/etc/opt/chrome/native-messaging-hosts/com.dannyvankooten.browserpass.json"
rm "/etc/chromium/native-messaging-hosts/com.dannyvankooten.browserpass.json"
rm "/usr/lib/mozilla/native-messaging-hosts/com.dannyvankooten.browserpass.json"
rm "$HOME/.config/google-chrome/NativeMessagingHosts/com.dannyvankooten.browserpass.json"
rm "$HOME/.config/chromium/NativeMessagingHosts/com.dannyvankooten.browserpass.json"
rm "$HOME/.mozilla/native-messaging-hosts/com.dannyvankooten.browserpass.json"
```

**Comment by LeonardoGentile** [comment]
thanks @dannyvankooten, so basically you are telling that getting rid of the browser extension would be sufficient, right? Without it these are just regular file, isn't it?

**Comment by dannyvankooten** [comment]
Exactly @LeonardoGentile, you can delete the local `browserpass` binary file too. It is the only thing that actually does something, but it will never run unless triggered by the browser extension. It should be in the same directory as where you ran the `install.sh` script from.

**Comment by LeonardoGentile** [comment]
👍
