### ISSUE TITLE
Q: How to install on FreeBSD CURRENT

### ISSUE THREAD

**Issue by gurucubano** [dannyvankooten/browserpass#100]
Hello,

What is the way to install it on FreeBSD? I've downloaded the sources 1.0.6, unpacked and run:
[guru@r314251-amd64 ~/browserpass-1.0.6]$ gmake browserpass
go build -o browserpass ./cmd/browserpass
bash: go: no se encontró la orden
gmake: *** [makefile:27: browserpass] Error 127

Any hints? Thanks

**Comment by gurucubano** [comment]
meanwhile I installed lang/go in my system, but it keeps saying:

$ gmake browserpass
go build -o browserpass ./cmd/browserpass
cmd/browserpass/main.go:8:2: cannot find package "github.com/dannyvankooten/browserpass" in any of:
	/usr/local/go/src/github.com/dannyvankooten/browserpass (from $GOROOT)
	/home/guru/go/src/github.com/dannyvankooten/browserpass (from $GOPATH)
cmd/browserpass/main.go:9:2: cannot find package "github.com/dannyvankooten/browserpass/pass" in any of:
	/usr/local/go/src/github.com/dannyvankooten/browserpass/pass (from $GOROOT)
	/home/guru/go/src/github.com/dannyvankooten/browserpass/pass (from $GOPATH)
gmake: *** [makefile:27: browserpass] Error 1

**Comment by gurucubano** [comment]
I got some help in the FreeBSD community and did:
$ cd
$ go get -u github.com/dannyvankooten/browserpass
$ GOPATH=/home/guru/go export GOPATH
$ cd $GOPATH/src/github.com/dannyvankooten/browserpass/cmd/browserpass
$ go build           [*]
$ ls -l
total 2884
-rwxr-xr-x  1 guru  wheel  2901409  3 jul.  13:02 browserpass
-rw-r--r--  1 guru  wheel      357  3 jul.  13:00 main.go

$ PATH=$PATH:$GOPATH/bin
$ go install
$ ls -l $GOPATH/bin
total 2880
-rwxr-xr-x  1 guru  wheel  2901409  3 jul.  13:03 browserpass

so far so good, but:

Now the installation requires the integration with the browser through
some script 'install.sh'; I looked for it and did:

$ bash src/github.com/dannyvankooten/browserpass/install.sh

Select your browser:
====================
1) Chrome
2) Chromium
3) Firefox
4) Vivaldi
1-4: 3

Installing Firefox host config
cp: /home/guru/go/src/github.com/dannyvankooten/browserpass/firefox-host.json: No such file or directory

Hmmm, where is the *.json file we need?
$ find ~/go -name *.json
./src/github.com/dannyvankooten/browserpass/chrome/host.json
./src/github.com/dannyvankooten/browserpass/chrome/manifest.json
./src/github.com/dannyvankooten/browserpass/chrome/policy.json
./src/github.com/dannyvankooten/browserpass/firefox/host.json
./src/github.com/dannyvankooten/browserpass/firefox/manifest.json
./src/github.com/dannyvankooten/browserpass/package.json
./src/github.com/dannyvankooten/browserpass/vendor/vendor.json

I fixed the above install.sh and copied over

$ cp src/github.com/dannyvankooten/browserpass/firefox/host.json /home/guru/.mozilla/native-messaging-hosts/com.dannyvankooten.browserpass.json

and modified the 'path' in it to show:

$ cat /home/guru/.mozilla/native-messaging-hosts/com.dannyvankooten.browserpass.json

{
  "name": "com.dannyvankooten.browserpass",
  "description": "Browserpass binary for the Firefox extension",
  "path": "/home/guru/go/src/github.com/dannyvankooten/browserpass/cmd/browserpass/browserpass",
  "type": "stdio",
  "allowed_extensions": [
     "browserpass@dannyvankooten.com"
   ]
}

Maybe the exec /home/guru/go/src/github.com/dannyvankooten/browserpass/cmd/browserpass/browserpass
should be copied to some better place;

Now install the 'browserpass' add-on from:
https://addons.mozilla.org/en-US/firefox/addon/browserpass/
(one must fake the User-agent string to, for example, Ubuntu)

After all this, it works fine with FreeBSD and and FF 52

**Comment by maximbaz** [comment]
Thanks, the issue with `install.sh` has been fixed in https://github.com/dannyvankooten/browserpass/pull/114 and the instructions on how to build for FreeBSD has been added in https://github.com/dannyvankooten/browserpass/pull/109. I'll thus close the issue. 

Feel free to send PR to further improve the instructions 🙂
