### ISSUE TITLE
Extract content script to find and fill login forms to its own repository

### ISSUE THREAD

**Issue by DamienCassou** [dannyvankooten/browserpass#107]
Hi,

I found your content script to find and fill login forms and decided to reuse that in the context of my own web extension. Would it make sense to extract that to its own project so people can just include it using package.json? I can take care of the extraction if you want to.

**Comment by maximbaz** [comment]
Hey, I think it makes sense to do this, unless the extraction would be very complicated because of tight coupling. If you want to try and extract it, please go ahead, I'll make sure not to delay reviewing the PR 🙂

**Comment by DamienCassou** [comment]
I will. First, I will see what others are doing.

**Comment by maximbaz** [comment]
I'll close the issue for cleanup purposes, since nobody else seems to be interested in this. Feel free to submit a PR if you still want to act on this 🙂
