### ISSUE TITLE
Ctrl+M doesn't work on Firefox

### ISSUE THREAD

**Issue by soren121** [dannyvankooten/browserpass#11]
Ctrl+M is already mapped to "mute tab" on Firefox, so I can't use it to autofill login fields. Would it be possible to change the key combo to something else, or add a setting to let the user remap it?

**Comment by soren121** [comment]
After looking further, it looks like the shortcut feature [is unsupported on Firefox](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands#commands). Maybe that should be noted in the readme?

**Comment by dannyvankooten** [comment]
Hi @soren121,

Thanks so much for looking into that. I am a little confused by the Firefox documentation as to whether shortcuts are not possible at all or if only "using media keys as shortcuts" is unsupported. I think it is the latter, so I will do some digging to see how to fix this. :)

**Comment by dannyvankooten** [comment]
Hey @soren121,

After some digging it seems like the current version of Firefox does not yet support mapping a shortcut to the "_execute_browser_action" command (which opens the pop-up). The good news is that [they are adding this in Firefox 52](https://blog.mozilla.org/addons/2016/11/18/webextensions-in-firefox-52/), so it will be a matter of weeks (maybe months?) until this works!
