### ISSUE TITLE
When only password text field is present, login fails

### ISSUE THREAD

**Issue by GJKrupa** [dannyvankooten/browserpass#111]
When the trying to fill in a page that only has a password prompt (e.g. the GitHub confirm password screen that shows when performing sensitive operations), login fails.  I'm guessing it's because the extension is filling the username into the password field.  I have verified the stored password is correct by using pass -c to copy the stored password into the clipboard.

**Comment by GJKrupa** [comment]
I'm using Chrome 57 on Ubuntu 16.04 (x64)

**Comment by arvindch** [comment]
Yep, this happens on the Gmail 2-step login screen, as well.

**Comment by mcnesium** [comment]
also on Mailman's List Administrator Password `<input name="adminpw" type="password">`

**Comment by emersion** [comment]
Also happens on ProtonMail's sensitive operation modal, where there's a field for the password and a field for 2FA.

**Comment by txsmith** [comment]
Also on the general Google account login page.

**Comment by maximbaz** [comment]
This has been fixed in `master`, I tested on Github confirm password screen and Google login page. Let me know if you spot a website where this doesn't work.

**Comment by aconthea** [comment]
@maximbaz Fyi, login does not work on https://www.namecheap.com/myaccount/login.aspx 

There are both username and password fields but browserpass only fills in the password and leaves the username empty.

**Comment by maximbaz** [comment]
Thanks for the heads up! Apparently I've fixed this earlier today together with the fix for #169, I'll release 2.0.3 very soon which will include the code fix.

**Comment by mcnesium** [comment]
You are doing a hell of a job on this these days. Thank you very much for your effort @maximbaz !
