### ISSUE TITLE
fill fields without forms

### ISSUE THREAD

**Issue by rolandoam** [dannyvankooten/browserpass#115]
some websites have a login system that does not uses a form (yes, shocker...). In these cases, because the script injected in the webpage tries to fill in the field that belongs to a form (https://github.com/dannyvankooten/browserpass/blob/master/chrome/script.browserify.js#L177) it will not find the password field. I'm not sure how to fix this without breaking behavior for other websites. Is there a hard requirement that an input field type password is going to be inside a form? is this just a heuristic to try to find the best field? Maybe if there is no password field, it could try relaxing the form-required restriction.

**Comment by rolandoam** [comment]
on a second read of the code, it seems that if the form is undefined, it should still include it in the results. Not sure why it's not working then. I'll try to add some debug code to find out when I have some time.

**Comment by maximbaz** [comment]
Could you provide examples of website where login doesn't use chrome? No doubt they exist, such examples will be useful for testing and I can't just find an example of top of my head.

**Comment by maximbaz** [comment]
I think I found a reason for this, it was actually pretty stupid. Should be fixed since v1.0.14.

If you find an example where the fields are still not being filled, please let me know.
