### ISSUE TITLE
browserpass doesn't work with password protected keys

### ISSUE THREAD

**Issue by inferiorhumanorgans** [dannyvankooten/browserpass#120]
Much like #13 I'm running into the issue where I can't get browserpass to fill in anything (it just hangs) on my mac.  Chrome and Firefox both fail.  If I run Chrome from the command line it still doesn't work.  If I run pass foo and go through its gpg prompts to put the password into the GNUPG agent and THEN run Chrome from that terminal window, browserpass works.

```
[Browserpass] 2017/08/17 15:46:23 exit status 2
gpg: decryption failed: No secret key
```

```
$ uname -a
Darwin SFOC02T87CDH03Q 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

$ gpg --version
gpg (GnuPG) 2.1.21
libgcrypt 1.8.0
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/.../.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

$ pass --version
============================================
= pass: the standard unix password manager =
=                                          =
=                  v1.7.1                  =
=                                          =
=             Jason A. Donenfeld           =
=               Jason@zx2c4.com            =
=                                          =
=      http://www.passwordstore.org/       =
============================================
```

**Comment by maximbaz** [comment]
It sounds to me like `gpg-agent` is not running or is stuck, and running `pass foo` somehow "revives" it. Could you see if `gpg-agent` process is running when you start Chrome, and if it is, try to kill it?

**Comment by inferiorhumanorgans** [comment]
I think the issue ended up being that browserpass wasn't getting the gpg agent path correct (path is not propagated).  I took it as a chance to write something with Rust instead (and add touch id support to pinentry-mac).

**Comment by maximbaz** [comment]
All right, thanks for the details. Since the issue ended up being the same as described in the last commends of #13, I'm going to close this issue and follow-up on posted workarounds in there. 

If this is incorrect, please let me know.

**Comment by brothermechanic** [comment]
same issue on latest gentoo

**Comment by erayd** [comment]
@brothermechanic This is nothing to do with browserpass - it's a gpg issue. Typically it means that `gpg-agent` is not running, or is not configured correctly, or you don't have a pinentry program properly configured.

**Comment by erayd** [comment]
@brothermechanic What happens when you use `pass` directly, rather than using browserpass?

**Comment by brothermechanic** [comment]
after entering gpg password in pass browserpass works
but by spend several time i need enter gpgkey password with pass agane

**Comment by brothermechanic** [comment]
may be i need configure gpg-agent?
can you give me an advice?

**Comment by max-baz** [comment]
I think you need to configure a GUI pinentry, check this out: https://github.com/browserpass/browserpass-native/#hints-for-configuring-gpg

**Comment by brothermechanic** [comment]
like this https://i.imgur.com/Jd1wX9E.png ?

**Comment by max-baz** [comment]
Yep! Now restart `gpg-agent` (or just reboot) and try to use Browserpass, it will trigger `gpg` which in turn should activate `gpg-agent` which in turn should show you a pinentry dialog.

If something is still not working, make sure that `gpg-agent` is actually running among processes, maybe you need to enable/activate it somehow.

**Comment by brothermechanic** [comment]
You my hero!
Thank you!
I did that and + did this instructions
https://wiki.gentoo.org/wiki/GnuPG#Using_a_GPG_agent
