### ISSUE TITLE
Cannot build: no chrome.crx generated

### ISSUE THREAD

**Issue by raxod502** [dannyvankooten/browserpass#127]
I followed the instructions in [Contributing](https://github.com/maximbaz/browserpass/blob/98d58bf3533fc766418436090fe5c41bac3a5a75/CONTRIBUTING.md), applying the following patch to commit https://github.com/maximbaz/browserpass/commit/98d58bf3533fc766418436090fe5c41bac3a5a75.

```diff
diff --git i/makefile w/makefile
index 84d267b..7d1e7cd 100644
--- i/makefile
+++ w/makefile
@@ -1,12 +1,12 @@
 SHELL := /usr/bin/env bash
-CHROME := `which google-chrome 2>/dev/null || which google-chrome-stable 2>/dev/null || which chrome 2>/dev/null`
+CHROME := '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'

 .PHONY: empty
 empty:

 .PHONY: chrome
 chrome:
-       $(CHROME) --pack-extension=./chrome --pack-extension-key=./chrome-browserpass.pem
+       $(CHROME) --headless --disable-gpu --pack-extension=./chrome --pack-extension-key=./chrome-browserpass.pem
        mv chrome.crx chrome-browserpass.crx

 .PHONY: firefox
```

I get the error:

```
% sudo make release
cp chrome/host.json chrome-host.json
cp firefox/host.json firefox-host.json
cp chrome/policy.json chrome-policy.json
'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' --headless --disable-gpu --pack-extension=./chrome --pack-extension-key=./chrome-browserpass.pem
mv chrome.crx chrome-browserpass.crx
mv: rename chrome.crx to chrome-browserpass.crx: No such file or directory
make: *** [chrome] Error 1
```

System and dependency information:

```
                -/+:.           raxod502
               :++++.           -------------------------------------
              /+++/.            OS: OS X El Capitan 10.11.6 15G1611 x86_64
      .:-::- .+/:-``.::-        Model: MacBookPro11,3
   .:/++++++/::::/++++++/:`     Kernel: 15.6.0
 .:///////////////////////:`    Uptime: 23 days, 4 hours, 2 minutes
 ////////////////////////`      Packages: 408
-+++++++++++++++++++++++`       Shell: zsh 5.4.1
/++++++++++++++++++++++/        Resolution: 3008x1692@2x, 1440x900@2x
/sssssssssssssssssssssss.       DE: Aqua
:ssssssssssssssssssssssss-      WM: Quartz Compositor
 osssssssssssssssssssssssso/`   WM Theme: Blue
 `syyyyyyyyyyyyyyyyyyyyyyyy+`   Terminal: iTerm2
  `ossssssssssssssssssssss/     Terminal Font: InputMono-Medium 14
    :ooooooooooooooooooo+.      CPU: Intel i7-4980HQ (8) @ 2.80GHz
     `:+oo+/:-..-:/+o+/-        GPU: Intel Iris Pro, NVIDIA GeForce GT 750M
                                Memory: 4945MiB / 16384MiB
```

Chrome 60.0.3112.113 (Official Build) (64-bit).

**Comment by maximbaz** [comment]
While this is undoubtedly an issue, a workaround you could use is "load unpacked extension", where you select a `chrome` directory. 

This is at least what I personally ended up doing, as I also had issue with this step (though a different one).

**Comment by maximbaz** [comment]
So we can't build the Chrome extension, because we lack `chrome-browserpass.pem` (it is not hosted on github, otherwise anyone would be able to upload the Chrome extension to the store). 

I've already gotten the collaborator permissions and will start looking in PRs in this repo today, so no need to use my fork anymore, and I'll ask @dannyvankooten for the pem key so that I will be able to publish updated extensions to the store - if not, we will have to find another way, e.g. I'll have to pack and publish it as another extension with the same name.

**Comment by raxod502** [comment]
With your changes to the makefile, I can now build successfully. Feel free to close this issue, or not (depending on whether you would like to use it for discussion of getting the pem key).

**Comment by maximbaz** [comment]
I can build it now too 🎉 

I'll use #117 to track updating extensions in Websore.
