### ISSUE TITLE
When using Yubikey, `pinentry` never pops open

### ISSUE THREAD

**Issue by tsnieman** [dannyvankooten/browserpass#128]
Background:
- I am using GNU/Linux
- I access my password store files using a Yubikey (via PIN prompt from my `pinentry`)
- Command-line access for `pass` works fine
- `browserpass` can be successfully installed (including native messaging)
- I see my password files when searching via `browserpass`

Current behavior:
- When I click on an entry in the `browserpass` list, I just get a "loading/spinner" and nothing else happens.

Expected behavior:
- When clicking on an entry in the `browserpass` list, my `pinentry` should be invoked and I should have to enter a PIN.

Is there something I'm missing about using Yubikey ("smartcard") for accessing `pass` via `browserpass`? Anyone else using a Yubikey getting `browserpass` to successfully pop their `pinentry`? How do I debug this?

**Comment by maximbaz** [comment]
I'm using Yubikey 4 Nano without problems on ArchLinux - don't think I did any extra configuration for browserpass. First of all, try to run extension from sources, what we have published in web store is outdated. If the issue persists, check if you have some error in browser console. Also right click on the extension icon > "Inspect popup" and see if there are any errors there. Are you using Chrome or Firefox extension by the way?

**Comment by tsnieman** [comment]
Ah, fantastic insight @maximbaz. I'm using Chrome, and I've manually installed from sources (as I saw there was an issue with the chrome extension being 1.0.5 being in the web store).

Using `inspect popup` reveals some fun things.

First, when I do `inspect popup`, the console already has an error before clicking anything:
```
Unchecked runtime.lastError while running browserAction.setIcon: Icon invalid.
```

When I click on a login entry (i created a fake one for github to test), I get the following:
```
console.log {message: "Native host has exited."}

Error in event handler for (unknown): TypeError: Cannot read property 'p' of undefined
    at fillLoginForm (chrome-extension://klfoddkbhleoaabpmiigbmpbjfljimgb/script.js:198:63)
    at chrome-extension://klfoddkbhleoaabpmiigbmpbjfljimgb/script.js:134:3
```

which corresponds to:

```
update(field('input[type=password]'), ${JSON.stringify(login.p)});
```

Which means `login` is undefined. `login` is the argument, passed from...
```
function getLoginData() {
	searching = true;
	logins = null;
	m.redraw();

	chrome.runtime.sendNativeMessage(app, { "action": "get", "entry": this }, function(response) {
		if( chrome.runtime.lastError) {
			console.log(chrome.runtime.lastError);
		}

		searching = false;
		fillLoginForm(response);
	});
}
```

I'm not sure if it's an error with my pass file formatting or with the native messaging host. I installed the native messaging host using `install.sh` from the repo (release 1.0.6). I have tried installing both without and with `sudo` without errors.

Any ideas on how I debug from here?

**Comment by maximbaz** [comment]
Try to pull the latest changes, I think you were unlucky to clone the repo when it had a merge conflict 🙂

**Comment by maximbaz** [comment]
If that is not the case, I'll try to come up with ideas on how to debug this further...

**Comment by tsnieman** [comment]
@maximbaz Alright, I got it working with a few caveats.

1. When using the `install.sh` script from `master`, the file directories are wrong (`chrome-host` vs `chrome/host`, etc). This PR would fix that: https://github.com/dannyvankooten/browserpass/pull/114

2. To get the `pinentry` to pop, my Yubikey had to be inserted **before I started Chrome**. If it wasn't inserted before I started Chrome, I simply got the "infinite spinner" problem.

3. I cannot remove the Yubikey and reinsert it while Chrome is running.

4. Not sure if this part is necessary, but I manually dropped in the chrome `.crx` extension file from the `1.0.6` release found on the Releases page. The `.crx` is not provided by `master`. (I did not use the release's `install.sh` file to install the native messaging host, I used the `master` repo/branch which I cloned)

Wondering if we should create another issue for "must have yubikey inserted before Chrome starts for native messaging host to work on Linux x64"?

**Comment by tsnieman** [comment]
Another comment to say: there's another issue at play here it seems, as I haven't removed by Yubikey and it has failed to continue to work with `browserpass`/native host messaging. I'll check back in if I figure out what's up.

**Comment by maximbaz** [comment]
That is certainly weird. Don't use `.crx` file from the releases for now, they are outdated, instead try the following:

In the repo:

```
$ git pull
$ make js
```

Then in Chrome:

- Go to chrome://extensions/
- Remove existing `browserpass` extension from there
- Click `Load unpacked extension`
- Select `browserpass/chrome` folder

Let me know if after this the issue reproduces. If it does, could you check that the error is exactly the same, `TypeError: Cannot read property 'p' of undefined` in `script.js` ?

**Comment by tsnieman** [comment]
After doing the instructions you provided above (`make js`/`Load unpacked extension`), I can no longer view the console because the "Inspect Popup" devtools close immediately after clicking one of  the entries. So, a regression in usage.

----

Unrelated to your previous comment, but did more testing/digging and found a reproducible problem: `browserpass` works fine in a new Chrome session (i.e. where Yubikey was inserted prior to session's start) for the first use, but completely breaks my yubikey until I logout/login to my current desktop environment.

**Comment by maximbaz** [comment]
This should help you retain the logs even if the "Inspect popup" is closing itself, I hope 🙂

![image](https://user-images.githubusercontent.com/1177900/30445059-2a77560a-9985-11e7-93a4-765f0204c68f.png)

Could you try to see if the logs contain an error? I'm so curious how browserpass manages to break your Yubikey 🙂

**Comment by tsnieman** [comment]
Using "preserve log" does not work; the window still closes and the console resets to  what you see in your screenshot.

**Comment by maximbaz** [comment]
I'm not entirely sure why the popup is closing now, but was not closing before, but what you could try just for experimental purposes is open `chrome/script.browserify.js`, comment the line `window.close()` in the very end of the file, run `make js` and redo the `Load unpacked extension` thing - the popup will not close after you select credentials, but with it the popup will not close as well.

Because without error message I'm not sure how else I could help 🙂

**Comment by tsnieman** [comment]
Well, after some further testing I think I might be having more issues with my desktop environment (`gnome-keyring` / `gpg-agent` / `ssh-agent`) up than with `browserpass`. I'm gonna close this for now but will reopen/comment if I learn anything new related to `browserpass` specifically. For now, killing and restarting my GPG agent when it inexplicably stops working seems to at least get me functional.

Thanks for your help @maximbaz.
