### ISSUE TITLE
When building locally, "Error talking to Browserpass host"

### ISSUE THREAD

**Issue by raxod502** [dannyvankooten/browserpass#129]
I followed the instructions in [Contributing](https://github.com/dannyvankooten/browserpass/blob/501d52c4e0d0b1cce8d725566503ee8f9ebbd28f/CONTRIBUTING.md) to build a local version of Browserpass using commit 6d614dc8d489edfbaf2798e5c65422618d0b905c. I ran `./install.sh` and dragged the `.crx` to `chrome://extensions`. However, the menu in Chrome just says `Error talking to Browserpass host`. I started Chrome from the console using

```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --enable-logging --v=1
```

but didn't get anything Browserpass-specific (I think):

```
2017-09-14 14:34:37.631 Google Chrome[42755:31556524] NSWindow warning: adding an unknown subview: <FullSizeContentView: 0x7fda1c7369f0>. Break on NSLog to debug.
2017-09-14 14:34:37.631 Google Chrome[42755:31556524] Call stack:
(
    "+callStackSymbols disabled for performance reasons"
)
2017-09-14 14:35:33.982 Google Chrome[42755:31556524] -_continuousScroll is deprecated for NSScrollWheel. Please use -hasPreciseScrollingDeltas.
2017-09-14 14:35:33.982 Google Chrome[42755:31556524] -deviceDeltaX is deprecated for NSScrollWheel. Please use -scrollingDeltaX.
2017-09-14 14:35:33.982 Google Chrome[42755:31556524] -deviceDeltaY is deprecated for NSScrollWheel. Please use -scrollingDeltaY.
2017-09-14 14:35:36.927 Google Chrome Helper[43158:31562422] Couldn't set selectedTextBackgroundColor from default ()
[42755:36611:0914/144252.776141:ERROR:connection_factory_impl.cc(386)] Failed to connect to MCS endpoint with error -106
[42755:36611:0914/173112.283741:ERROR:connection_factory_impl.cc(386)] Failed to connect to MCS endpoint with error -106
2017-09-14 17:34:08.809 Google Chrome Helper[47510:31584157] Couldn't set selectedTextBackgroundColor from default ()
```

Any way I can debug further?

### System information

```
                -/+:.           raxod502
               :++++.           -------------------------------------
              /+++/.            OS: OS X El Capitan 10.11.6 15G1611 x86_64
      .:-::- .+/:-``.::-        Model: MacBookPro11,3
   .:/++++++/::::/++++++/:`     Kernel: 15.6.0
 .:///////////////////////:`    Uptime: 24 days, 6 hours, 39 minutes
 ////////////////////////`      Packages: 404
-+++++++++++++++++++++++`       Shell: zsh 5.4.1
/++++++++++++++++++++++/        Resolution: 1680x1050@2x
/sssssssssssssssssssssss.       DE: Aqua
:ssssssssssssssssssssssss-      WM: Quartz Compositor
 osssssssssssssssssssssssso/`   WM Theme: Blue
 `syyyyyyyyyyyyyyyyyyyyyyyy+`   Terminal: iTerm2
  `ossssssssssssssssssssss/     Terminal Font: InputMono-Medium 14
    :ooooooooooooooooooo+.      CPU: Intel i7-4980HQ (8) @ 2.80GHz
     `:+oo+/:-..-:/+o+/-        GPU: Intel Iris Pro, NVIDIA GeForce GT 750M
                                Memory: 4376MiB / 16384MiB
```

Chrome version:

Google Chrome | 60.0.3112.113 (Official Build) (64-bit)
-- | --
Revision | 95c454326a7a3153e984e50a4719924968490717-refs/branch-heads/3112@{#744}

**Comment by maximbaz** [comment]
So I'm also learning how things work here, but this is where I would start:

When you ran `make release`, you also compiled a host binary, `browserpass-darwinx64` among them is what you need. The path to this binary should be defined in either `/Library/Google/Chrome/NativeMessagingHosts` or `$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts`, depending if you ran `make release` as root or as a normal user (this is defined in `install.sh`). Open that file and make sure that the path to the host binary is correct.

**Comment by raxod502** [comment]
This is the log I get from the makefile:

```
browserpass[master*] % make release
"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" --disable-gpu --pack-extension=./chrome
rm ./chrome.pem
mv chrome.crx chrome-browserpass.crx
cp chrome/{*.html,*.css,*.js,*.png,*.svg} firefox/
mkdir -p release
zip -jFS "release/chrome" chrome/* chrome-browserpass.crx
updating: chrome-browserpass.crx (deflated 3%)
zip -jFS "release/firefox" firefox/*
updating: background.js (deflated 49%)
updating: content.html (deflated 44%)
updating: icon-key.svg (deflated 38%)
updating: icon-lock.png (deflated 2%)
updating: icon-lock.svg (deflated 42%)
updating: icon-search.svg (deflated 38%)
updating: inject.browserify.js (deflated 60%)
updating: inject.js (deflated 58%)
updating: script.browserify.js (deflated 59%)
updating: script.js (deflated 72%)
updating: styles.css (deflated 59%)
zip -FS "release/browserpass-linux64" browserpass-linux64 *-host.json chrome-browserpass.crx install.sh chrome-policy.json README.md LICENSE
        zip warning: name not matched: *-host.json
        zip warning: name not matched: chrome-policy.json
updating: chrome-browserpass.crx (deflated 3%)
zip -FS "release/browserpass-darwinx64" browserpass-darwinx64 *-host.json chrome-browserpass.crx install.sh README.md LICENSE
        zip warning: name not matched: *-host.json
updating: chrome-browserpass.crx (deflated 3%)
zip -FS "release/browserpass-openbsd64" browserpass-openbsd64 *-host.json chrome-browserpass.crx install.sh README.md LICENSE
        zip warning: name not matched: *-host.json
updating: chrome-browserpass.crx (deflated 3%)
zip -FS "release/browserpass-freebsd64" browserpass-freebsd64 *-host.json chrome-browserpass.crx install.sh README.md LICENSE
        zip warning: name not matched: *-host.json
updating: chrome-browserpass.crx (deflated 3%)
browserpass[master*] % ./install.sh

Select your browser:
====================
1) Chrome
2) Chromium
3) Firefox
4) Vivaldi
1-4: 1

Installing Chrome host config
Native messaging host for Chrome has been installed to /Users/raxod502/Library/Application Support/Google/Chrome/NativeMessagingHosts.
```

In the `/Users/raxod502/Library/Application Support/Google/Chrome/NativeMessagingHosts` directory, I have a file `com.dannyvankooten.browserpass.json` with the following contents:

```
{
  "name": "com.dannyvankooten.browserpass",
  "description": "Browserpass binary for the Chrome extension",
  "path": "/Users/raxod502/files/code/web/browserpass/browserpass-darwinx64",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://jegbgfamcgeocbfeebacnkociplhmfbk/",
    "chrome-extension://klfoddkbhleoaabpmiigbmpbjfljimgb/"
  ]
}
```

Indeed, the file exists and is executable:

```
% l /Users/raxod502/files/code/web/browserpass/browserpass-darwinx64
Permissions Size User     Date Modified Name
.rwxr-xr-x  2.9M raxod502 14 Sep 14:30  /Users/raxod502/files/code/web/browserpass/browserpass-darwinx64
```

**Comment by maximbaz** [comment]
I tried to follow your steps, had exactly the same issue, then I decided to remove the global browserpass that I had installed from package manager, and I _still_ had the same `Error talking to Browserpass host` error, and then I discovered that while I do have `NativeMessagingHosts` in my user folder with correct path to the binary, I _also_ had `NativeMessagingHosts` installed for the root user, and it had wrong path to binary and I assume it took precedence. When I deleted that directory (`/Library/Google/Chrome/NativeMessagingHosts` in your case) as well as policies directory (`/Library/Google/Chrome/policies` in your case), restarted Chrome and voila, everything works :)

**Comment by maximbaz** [comment]
After #134 I realized that there is actually another reason why you get this error.

See those two IDs in `com.dannyvankooten.browserpass.json` in `allowed_origins` section? Since you don't have a pem key for neither of those IDs, what you get when you do a `make release` is an extension with a new random ID. This ID is not whitelisted, and thus has no access to native host.

You have two options:

1. If you are only interested in backend, pull latest `master` to get a new ID that I put in there, this ID is based on a key that I generated for myself. Then take a `.crx` file from the latest release, it was built with my `.pem` file and thus has the same whitelisted ID.
2. If you want to be able to rebuild both backend and frontend locally, `make release` to compile your own `.crx` file, drag it into Chrome and copy the ID. Then create a third entry in `com.dannyvankooten.browserpass.json` in `allowed_origins` section and add your ID there.

**Comment by raxod502** [comment]
I've now gotten time to look at this again. The `chrome://extensions` page looks like this:

![image](https://user-images.githubusercontent.com/6559064/30655206-1cd92942-9de5-11e7-9378-75a99f0cc1e8.png)

(and that is the only browserpass extension installed; I got rid of the one from the web store, so this one is my local .crx). Then I modified my `com.dannyvankooten.browserpass.json` to look like this:

```json
{
  "name": "com.dannyvankooten.browserpass",
  "description": "Browserpass binary for the Chrome extension",
  "path": "/Users/raxod502/files/code/web/browserpass/browserpass-darwinx64",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://jegbgfamcgeocbfeebacnkociplhmfbk/",
    "chrome-extension://klfoddkbhleoaabpmiigbmpbjfljimgb/",
    "chrome-extension://onllnncpoocmmodpjomhnhnkhndejmpf"
  ]
}
```

After restarting Chrome, unfortunately, I still get the same error message.

**Comment by raxod502** [comment]
Wow, ok, I have no excuse for that. When I put a trailing slash on the `allowed_origins` URL, it works.

**Comment by maximbaz** [comment]
I've also gotten to know the project better, and I'm reworking the CONTRIBUTING.md as well as the makefile in https://github.com/dannyvankooten/browserpass/pull/149.

Basically, I believe users should not usually compile the `crx` file, but only run `make` to compile unpacked extensions for Chrome and Firefox + host application. The unpacked extension is already allowed to access the host app, so no other changes are needed.
