### ISSUE TITLE
1.0.8 fails to install.  1.0.8 crx has issues also

### ISSUE THREAD

**Issue by duffydack** [dannyvankooten/browserpass#134]
Archlinux and chromium using release pkg 1.0.8.
install as local user
Select your browser

1) Chrome
2) Chromium
3) Firefox
4) Vivaldi
1-4: 2

Installing Chromium host config
cp: cannot stat '/home/dean/Downloads/1.0.8/chrome/host.json': No such file or directory

edited install.sh, corrected the line
cp "$DIR/chrome/host.json" "$TARGET_DIR/$APP_NAME.json", to 
cp "$DIR/chrome-host.json" "$TARGET_DIR/$APP_NAME.json"
and the line
cp "$DIR/chrome/policy.json" "$TARGET_DIR"/../policies/managed/"$APP_NAME.json", to
cp "$DIR/chrome-policy.json" "$TARGET_DIR"/../policies/managed/"$APP_NAME.json"

succeeds.
Installing Chromium host config
Native messaging host for Chromium has been installed to /home/dean/.config/chromium/NativeMessagingHosts.

Drag n drop the crx file for release 1.0.8 into chromium, install, try to access via lock icon, and get Error talking to Browserpass host
Tried sudo ./install for system-wide install, succeeds.  Run chromium, extension 1.0.5 already installed and works.

Release pkg 1.0.6 has no issue as install file is correct already and crx file is 1.0.5 which seems only recent working version.

**Comment by maximbaz** [comment]
Thank you @duffydack, I believe I fixed both issues. Could you please delete the old releases and try out the v1.0.9?

**Comment by duffydack** [comment]
Working perfectly for local install.  System-wide install still uses 1.0.5, so means having 2 extensions for the same thing which is not ideal, but both work.
Thanks

**Comment by maximbaz** [comment]
Thanks. We have had quite a few bug fixes and improvements since 1.0.5, it would be a pity to force people to keep using it. 

I relaxed the policy so that automatic installation of the obsolete extension is not forced anymore (until I find a way to update extension in webstore - #117). Forcing people to install an obsolete extension does more harm than good.

@duffydack could you please test v1.0.11? 🙂

**Comment by duffydack** [comment]
sytstemwide install no longer forces old extension, and drag n drop newer extenision works.  Thanks..
Just need the AUR pkg to follow suit now.

**Comment by duffydack** [comment]
If updating the extension in store is not possible, couldn't you just make another?

**Comment by chrboe** [comment]
@duffydack see https://github.com/dannyvankooten/browserpass/issues/83#issuecomment-329853375

**Comment by duffydack** [comment]
I see.  Well drag drop manually is no great hardship I guess.  Working nicely now. which is the main

**Comment by maximbaz** [comment]
Thanks for reporting and all the testing 😉
