### ISSUE TITLE
RFC: Guess config directory in install.sh?

### ISSUE THREAD

**Issue by chrboe** [dannyvankooten/browserpass#136]
I was wondering if we could just "guess" the config directory for each browser (as in, `[[ -d ~./config/google-chrome ]] # put extension there`) 

The upside would be that
1. We could get rid of the browser selection prompt (or replace it with `Chrome detected, install for Chrome? [y/n]` type prompts)
2. We could properly detect development/canary/testing versions (#110) by just adding the config path to an array
3. People who use multiple browsers (for whatever reason) don't have to execute the script twice

The only downside I can see is that people might only want to install the extension for one particular browser, but that could be fixed by the prompts suggested in 1.

**Comment by maximbaz** [comment]
I like the idea, ideally have a map defined somewhere on top with browser names and their locations (so that it's easy to add new entries), and then a generic loop for all entries doing the work. Prompt is a good idea, let's do it.

**Comment by qbit** [comment]
I think it would make sense to do this.

**Comment by chrboe** [comment]
Little update on this: I've implemented a rough draft of how this could look, but I'm unable to test it right now. Once I get my hands on a Linux machine again I'll try it out and submit a PR.

**Comment by maximbaz** [comment]
This install script has been mentioned in a few other tickets recently, and remembering about this ticket and the fact that we had some issues with discovering browsers based on existence of configuration folders (details in #147), I'm wondering if this is really worth doing after all.

Point number 3 (having to restart script for multiple browsers) is a valid flaw, but maybe we should just allow typing multiple digits at the same time? 

```
Select your browser:
====================
1) Chrome
2) Chromium
3) Firefox
4) Vivaldi
1-4: 1 3 <Enter>
```

If we can refactor the code to simplify adding more browsers, that of course is nice too.

**Comment by maximbaz** [comment]
I think I'm going to close this and the PR due to the reasons above, let me know if you want to follow-up on any of the ideas above.
