### ISSUE TITLE
Unchecked runtime.lastError while running browserAction.setIcon: Icon invalid.

### ISSUE THREAD

**Issue by mschaaf** [dannyvankooten/browserpass#142]
I have this error in the javascript console:

`Unchecked runtime.lastError while running browserAction.setIcon: Icon invalid.`

I am not sure if this makes something not work but would like to report it to get handled.

**Comment by chrboe** [comment]
What OS and browser are you using? Did you download a release or build from source? If the former, what version of browserpass are you running, if the latter, what commit did you build from?

**Comment by maximbaz** [comment]
I have always seen that in Chrome popup, don't think it is causing any trouble, but a valid annoyance that needs to be fixed at some point.

![image](https://user-images.githubusercontent.com/1177900/30583343-1cf014f4-9d27-11e7-971b-e0898f64345d.png)

**Comment by chrboe** [comment]
[Related?](https://stackoverflow.com/questions/38457208/chrome-extension-error-unchecked-runtime-lasterror-while-running-browseraction)

**Comment by maximbaz** [comment]
Probably because we set `svg` icon, and Chrome doesn't like `svg` format 🙂

https://github.com/dannyvankooten/browserpass/blob/05fe33979365c7eb14fbc66298bfe5a9fde08071/chrome/script.browserify.js#L12

I wonder if that line can be entirely removed, or it is needed for Firefox 🤔

**Comment by mschaaf** [comment]
I am on linux 16.04.1-Ubuntu,
browserpass is version 1.0.5 and
chrome Version 61.0.3163.91

**Comment by maximbaz** [comment]
I simply deleted that line, don't see any difference in Chrome or Firefox.

**Comment by shubham-jain4** [comment]
Try changing the original size of image to 128px. This is some bug in chrome that it doesn't parse image which is  greater than 192px.
