### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by chrboe** [dannyvankooten/browserpass#143]
Since we support a pretty wide variety of OS-and-browser combinations, and it isn't always clear which OSes/browsers bug reporters are using, I suggest we add an issue template. See here for an example: https://github.com/neovim/neovim/blob/master/ISSUE_TEMPLATE.md

I imagine it could be structured something like this:

### General information
* Operating system + version:
* Browser + version:
* Built from source?
* Browserpass version or commit if built from source:

### What happened instead?

---

Opinions/Improvement ideas?

**Comment by maximbaz** [comment]
#145
