### ISSUE TITLE
The search box is not autofocused in FF when popup is opened

### ISSUE THREAD

**Issue by maximbaz** [dannyvankooten/browserpass#155]
### General information

* Operating system + version: ArchLinux
* Browser + version: FF 55.0.3
* If installed an official release, put a release version: 
* If built from sources, put a commit id (`$ git describe --always`): https://github.com/dannyvankooten/browserpass/commit/c3a6279f145e4fa03cbc6db426521279bdf6dfc2
* Browserpass extension version as reported by your browser: 1.0.15

---

### Exact steps to reproduce the problem
1. Install the extension on Firefox
2. Hit the hotkey <kbd>Alt+Shift+L</kbd>

### What should happen?

The search input box should autofocus, ready to receive search term, just like on Chrome.

### What happened instead?

Need to press <kbd>Tab</kbd>, <kbd>Tab</kbd> to get to the search box.

-----

May be somewhat related to #40.

**Comment by turboMaCk** [comment]
I think we can use [this](https://mithril.js.org/lifecycle-methods.html#oncreate) lifecycle hook on the very top component to make a check if the input is selected. In case it's not we can use standard `DOM` API to do select via script. What do you think?

**Comment by turboMaCk** [comment]
Also, I agree that this https://github.com/dannyvankooten/browserpass/issues/40#issuecomment-301186768 feature would be nice. Anyway, I would suggest to do it one by one. First, start with solving autofocus issue and then adding detection about what should be focused once popup is opened.

**Comment by maximbaz** [comment]
I'm fine with doing it one by one :+1:

**Comment by turboMaCk** [comment]
I'll start working on it after dinner then. I think it won't take much time.

**Comment by maximbaz** [comment]
Awesome job with this bug :+1: 
Wanna tackle https://github.com/dannyvankooten/browserpass/issues/40#issuecomment-301186768 next? There's no rush, whenever you have time 🙂

**Comment by phryneas** [comment]
Hey there, I was just experiencing the same problem and the mailing list led me to this open Issue in the Firefox Bug Tracker - you might want to monitor that too :)
https://bugzilla.mozilla.org/show_bug.cgi?id=1324255
