### ISSUE TITLE
Problem with Alt+Shift+L on Mac

### ISSUE THREAD

**Issue by dekoza** [dannyvankooten/browserpass#157]
### General information
* Operating system + version: MacOS X 10.12.6
* Browser + version: Chrome 60.0.3112.113
* If installed an official release, put a release version: 1.0.5?
* Browserpass extension version as reported by your browser: 1.0.5

---

### Exact steps to reproduce the problem
1. Have "Polish pro" keyboard profile active 
2. Activate an input field (like on forum, etc.)
3. Try entering the letter "Ł" by pressing Alt+Shift+L

### What should happen?
The letter "Ł" should be entered into field.

### What happened instead?
Searchbar of browserpass appeared.

After turning browserpass extension off, the letter "Ł" can be entered normally. Adding configurable shortcuts would be helpful.

**Comment by maximbaz** [comment]
The shortcut is configurable on Chrome, but it's a bit hidden 🙂

Go to `chrome://extensions/`, scroll to the bottom, click on `Keyboard shortcuts` and `browserpass` will be among the first entries there.

**Comment by maximbaz** [comment]
Closing, let me know if you have additional questions.
