### ISSUE TITLE
When installing Chrome extension by dragging, the installed NativeMessagingHost is incorrect

### ISSUE THREAD

**Issue by sharms** [dannyvankooten/browserpass#16]
If a extension is dragged from the release package to the extensions tab, the ID is different than `.config/google-chrome/NativeMessagingHosts/com.dannyvankooten.browserpass.json` lists under the `allowed_origins` field

**Comment by maximbaz** [comment]
This is an old issue and I don't think it is valid anymore, as I've seen people installing extension from releases (example: https://github.com/dannyvankooten/browserpass/issues/128#issuecomment-329543935), so I'll close it. 

Let me know if this is not solved for you, and I'll reopen.
