### ISSUE TITLE
KEYBOARD SHORTCUT CHANGED!! - Suggest a better one

### ISSUE THREAD

**Issue by maximbaz** [dannyvankooten/browserpass#160]
<kbd>Alt+Shift+L</kbd> causes so [many](https://github.com/dannyvankooten/browserpass/issues/60) [troubles](https://github.com/dannyvankooten/browserpass/issues/51), that I think it's time to think about a better default. The current shortcut was introduced in #11.

Rules of the game:
- Read the issues to understand what drives people to complain (e.g. <kbd>Alt+Shift</kbd> conflicts with international layouts)
- The new shortcut should not conflict with a common browser functionality - in Chrome and in Firefox.
- There are browser restrictions on [what keys can be used](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands#Key_combinations).

I personally use <kbd>Ctrl+Shift+O</kbd>, but I know that it conflicts with opening a bookmark manager in Chrome, so not a perfect candidate.

Make your suggestions!

**Comment by chrboe** [comment]
Good idea. I can also add to the list of issues that Lenovo laptops dump a debug log of the touchpad driver upon pressing <kbd>Alt+Shift+L</kbd>, so it really isn't ideal 🙂

**Comment by ainola** [comment]
I prefer minimal keyboard chording/keeping modifiers to a minimum. How about a combination that's pretty much guaranteed not to conflict with the browser, like `Ctrl+grave`? That's pretty easy to execute with one hand.

**Comment by chrboe** [comment]
@ainola I agree about the minimal modifiers thing, although we should also consider non-en-US keyboard layouts. (Try pressing <kbd>Ctrl+\</kbd> on a German keyboard without breaking your fingers 😉)

**Comment by maximbaz** [comment]
New discovery: there are browser restrictions on [what keys can be used](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands#Key_combinations). Grave, slash and backslash are not among them.

----------

Key combinations must consist of two or three keys:
- modifier (mandatory, except for function keys). This can be any of: "Ctrl", "Alt", "Command", "MacCtrl".
- secondary modifier (optional). If supplied, this must be "Shift".
- key (mandatory). This can be any one of:
    - the letters A-Z
    - the numbers 0-9
    - the function keys F1-F12
    - Comma, Period, Home, End, PageUp, PageDown, Space, Insert, Delete, Up, Down, Left, Right

**Comment by maximbaz** [comment]
My suggestions:
- <kbd>Ctrl+Shift+E</kbd> - simple enough to type with one hand
- <kbd>Ctrl+Shift+L</kbd> - similar enough to the current shortcut

**Comment by chrboe** [comment]
<kbd>Ctrl+Shift+E</kbd> clashes with Pushbullet, a pretty popular extension ([1m+ users](https://chrome.google.com/webstore/detail/pushbullet/chlffgpmiacpedhhbkiomidkjlcfhogd)).

<kbd>Ctrl+Shift+L</kbd> works as far as I can tell (no clashes on my system at least).

**Comment by maximbaz** [comment]
I'll do the following: I change the default to <kbd>Ctrl+Shift+L</kbd>, but leave the issue open for a while. 

Those who come to Github to complain about the problems with new shortcut will easily find this ticket and explain why it is a bad hotkey. 

If we don't hear complaints for a while, we will consider the matter resolved 🙂

**Comment by maximbaz** [comment]
Looks like everyone is happy with the current shortcut 😊 thus closing.

**Comment by juicetin** [comment]
As a friendly heads up for anyone who comes across this in future:

This shortcut overlaps with i3 window vertical resizes. It's a default of the window manager and changing the shortcut for that one function isn't really a sane option - short of changing the shortcut and reinstalling it yourself each time the repo changes (or IIUC in the case of firefox, each time you restart firefox), you'll probably be clicking on the icon manually

**Comment by maximbaz** [comment]
Thanks for the heads-up. I should add that the problem is more annoying to Firefox users who are stuck with the default shortcut, in Chrome you can override the default one and configure your favorite shortcut.

chrome://extensions/ and in the bottom right there is "Keyboard shortcuts".

**Comment by juicetin** [comment]
Thanks for adding that! Forgot to mention the thing with Firefox, as I first encountered it in that browser. Back on Chrome now due to reasons, so the ability to override the shortcut again is definitely nice!
