### ISSUE TITLE
Support for ChromeOS

### ISSUE THREAD

**Issue by duffydack** [dannyvankooten/browserpass#162]
Having just discovered chromebrew, and even a prebuilt version of 'pass' for it, I thought it would be cool to add support.  Have everything needed, git, gpg, pass all tested working in a chromeOS developer shell.
I realise however that the pinentry program needed by gpg would only be able to support tty as GUI wouldn't work with chromeOS, or would it?  If not, then it would need unlocking beforehand, and maybe having the ttl cache set to last the whole session.

**Comment by maximbaz** [comment]
The honest answer is "I have no idea, maybe?..." 🙂

Would you be willing to investigate this? I can guide you as much as I can. I don't have chromeOS to test, so without you there isn't much we can do 🙂

The primary challenge I think is to find how to compile a Go binary for Chrome OS. In the `makefile` copy-paste the entry for `browserpass-linux64`, and adjust `GOOS` and `GOARCH` - we need to find the pair of values that works for ChromeOS.

https://github.com/dannyvankooten/browserpass/blob/d18ceff62f117d673cfcd96611aa26fde5f60d37/makefile#L34-L35

Once you change the values, save the file and run `make browserpass-chromeos64`, and test if the compiled binary works. I recommend to test using [chrboe/native.pl](https://github.com/chrboe/native.pl).

The possible values for `GOOS` and `GOARCH` are listed [here](https://github.com/golang/go/blob/6f1724ff415a85b3329806c0c9a3e5e46afac317/src/go/build/syslist.go#L7-L8).

**Comment by duffydack** [comment]
I've actually done all of this on a regular laptop with neverware cloudready on usb stick.  You can install it to hard drive or use live, I used live.  I do own Chromebook but it's been wiped and arch installed, but looking at getting another later.  
Looking at the projects package list there is a Go pkg.  I will delve into it as you asked tomorrow, but if you wanna look into it, just boot usb, login as guest, ctrl alt t for terminal, type 'shell' and follow instructions on
https://github.com/skycocker/chromebrew
Really quite easy and simple.

**Comment by duffydack** [comment]
Right, it seems to build, but I'm having trouble with native.pl
I added the 'go' package, did a go get -u 'url', edited makefile, copied the section and called it browserpass-cros64, did make browserpass-cros64 which said
'env GOOS=linux GOARCH=amd64 go build -o browserpass-cros64 ./cmd/browserpass'
I have a binary 'browserpass-cros64'.  I grabbed native.pl script, ran 'perl native.pl browserpass-cros64 {\"test\"}' which returned
open3: exec of browserpass-cros64 failed: No such file directory at native.pl line 95

**Comment by maximbaz** [comment]
Assuming both perl script and compiled browserpass are in the same folder, try providing relative path. I run it like this actually: 

```
chmod +x native.pl
./native.pl ./browserpass-cros64 {"test"}
```

**Comment by maximbaz** [comment]
It would be very cool if GOOS=linux and GOARCH=amd64 are the values that actually work, it would mean you can just grab the release for Linux and it should work for chromeOS too, no extra effort required.

**Comment by duffydack** [comment]
Must be a chromeos shell thing (it's bash tho), but it doesn't allow to run with "./", I have to use perl native.pl.  If I use perl native.pl ./browserpass-cros64 it givesopen3: 
exec of ./browserpass-cros64 failed: Permission denied at native.pl line 95
I have permissions, it's set to +x, even sudo gives same error.  I'm about read to give up :)

**Comment by maximbaz** [comment]
I'll get back to you in an hour to try something else. In meanwhile, could you actually try to install the release for Linux and see if it works? Please take the file from #159.

**Comment by chrboe** [comment]
AFAIK ChromeOS is based on Gentoo, so it **should** just work out of the box with GOOS=linux.

Regarding the native.pl thing, could you run `which perl` and give me the output please? @duffydack

**Comment by duffydack** [comment]
Well, chromeOS is linux (gentoo), it's just stripped down of compiler and stuff, which chromebrew enables.
If git, gpg and pass all build and work then I can't see any reason for browserpass not to compile and work.

Tried the newer browserpass release, get "install.sh: 117: Bad substitution"

**Comment by duffydack** [comment]
which perl = /usr/local/bin/perl
and ls -lah https://pastebin.com/Du35JLGu

**Comment by chrboe** [comment]
> which perl = /usr/local/bin/perl

That might be your issue, the script is trying to execute `/usr/bin/perl`. I'll try and fix that another day, but it should still work using `perl native.pl`. 

The permission denied error is really weird, looking at your permissions it seems that everything should be good to go in that regard. Maybe something's wrong with the ChromeOS binary 🤔 

Either way, it should still work with the Linux binary. 

Ah, actually, I think I know what's wrong...  Can you post the output of `uname -s`?

**Comment by duffydack** [comment]
uname is Linux
bash is bash 4.3.42(1)-release (x86_64-cros-linux-gnu_
I have to go for the day, I'll try more tonight if I can.  This isn't a must have feature, I don;t have another chromebook yet, hence I'm doing all this on cloudready, which is 99.999% chromeOS.  
Later.

**Comment by chrboe** [comment]
Huh, nevermind, I don't know what's wrong 😄

Alright, I'll try and investigate the install.sh issue in the meantime. Thanks for your cooperation so far 🙂

**Comment by chrboe** [comment]
@duffydack Maybe this is related to your use case: https://stackoverflow.com/a/20616103/3691422 (even though we're using `/usr/bin/env bash`, but maybe ChromeOS is even mangling that).

Can you try running `bash install.sh`?

**Comment by maximbaz** [comment]
@duffydack another test to check that the host app works for you. Run this on a binary that you took from #159.

```
./browserpass-linux64 < ./request.hex.txt
```

[request.hex.txt](https://github.com/dannyvankooten/browserpass/files/1344121/request.hex.txt)

**Comment by duffydack** [comment]
Well I know that doesn't work, same as sh install.  Not near pc, can't remember what it was, something to do with HEAD, which I know it's git, but git works I know that much.

**Comment by duffydack** [comment]
chronos@localhost ~/go/src/github.com/dannyvankooten/browserpass $ ./browserpass-cros64
bash: ./browserpass-cros64: Permission denied
chronos@localhost ~/go/src/github.com/dannyvankooten/browserpass $ sh browserpass-cros64
browserpass-cros64: 1: ELF: not found
browserpass-cros64: 5: Syntax error: "(" unexpected
chronos@localhost ~/go/src/github.com/dannyvankooten/browserpass $ go browserpass-cros64
go: unknown subcommand "browserpass-cros64"
Run 'go help' for usage.
chronos@localhost ~/go/src/github.com/dannyvankooten/browserpass $ bash browserpass-cros64
browserpass-cros64: browserpass-cros64: cannot execute binary file
chronos@localhost ~/go/src/github.com/dannyvankooten/browserpass $

**Comment by maximbaz** [comment]
Browserpass is an independent executable, it can only be executed a `./browserpass`, not via `sh/go/bash`. I'm wondering if you are hosting this code on a partition that is mounted with `noexec` flag? Try running `mount` and check that there is no `noexec` flag.

**Comment by duffydack** [comment]
Damnit, why didn't I think of that... I copied the native.pl and browserpass-linux64 to /usr/local/bin and ran...success

chronos@localhost /usr/local/bin $ perl native.pl browserpass-linux64 {\"action\": \"search\", \"domain\": \"test\"}
Request: |  {"action":"search","domain":"test"}
Result:  |  ["test","test.com"]
Errors:  |  -

chronos@localhost /usr/local/bin $ ./native.pl ./browserpass-linux64 {\"action\": \"search\", \"domain\": \"test\"}
bash: ./native.pl: /usr/bin/perl: bad interpreter: No such file or directory

**Comment by maximbaz** [comment]
Awesome! Now do you still have the issues with `./install.sh` if you unpack the release archive for linux somewhere in `/usr/local/bin` and run `./install.sh` there?

**Comment by duffydack** [comment]
put in /usr/local/tmp and ran ./install.sh
chose chromium and chrome which made the files in /home/chronos/user/.config/NativeMessagingHosts but the extension fails to talk to host.  I don't know how chrome(ium) OS would identify the browser since it's an OS.  Getting somewhere now...

**Comment by maximbaz** [comment]
Do you have any other files in `/home/chronos/user/.config/`?

**Comment by duffydack** [comment]
No, I don't think it's used the same as other Os's

**Comment by maximbaz** [comment]
So you need to find a correct folder now 🙂 

Try this: `locate QuotaManager-journal` - it's just one of many files that I have in `~/.config/chromium/Default` folder, if you find something, that is likely the correct path.

**Comment by duffydack** [comment]
As i suspected, in $HOME (/home/chronos/user).  The partition layout and folder structure of cros is very different.  You can only see /home/chronos/user via terminal, things like Files app only show Google Drive and Downloads folder (in /home/chronos/user)

**Comment by maximbaz** [comment]
If you located the correct folder, try to put it in one of the two lines here (depends on what you select when you run the `./install.sh`):

https://github.com/dannyvankooten/browserpass/blob/04199ddfd8bf6601101e252cd65ee9362d4c1e0b/install.sh#L23-L24

If that succeeds, we will add there just another entry called `TARGET_DIR_CHROME_OS`.

**Comment by duffydack** [comment]
QuotaManager-journal is empty btw,     QuotaManager is a sqlite3 file

**Comment by duffydack** [comment]
Already tried that, doesn't work..

**Comment by maximbaz** [comment]
https://stackoverflow.com/a/34462129

> Chrome OS does not support third-party native messaging hosts

Disappointing... This answer is from 2015 though, maybe something changed since then...

**Comment by duffydack** [comment]
Well that's that then!  Pity, so close.

**Comment by maximbaz** [comment]
Indeed, unfortunately! Maybe you can consider submitting a feature request for Chrome OS team?

**Comment by duffydack** [comment]
If I can find such a page,  I'll try.  Thanks anyway
