### ISSUE TITLE
Extension broke after upgrading to 2.0.0 - Error talking to browserpass

### ISSUE THREAD

**Issue by maximbaz** [dannyvankooten/browserpass#165]
We had to upload extension under a new name, delete the current extension and install the new one!

Chrome - [link](https://chrome.google.com/webstore/detail/browserpass-ce/naepdomgkenhinolocfifgehidddafch).
Firefox - [link](https://addons.mozilla.org/en-US/firefox/addon/browserpass-ce/).

Details in #117.

-----

Didn't help? Maybe your issue is... #172?

**Comment by D3N14L** [comment]
Just wanted to drop a quick: Thank you! 
With version 2.0.0 browserpass works like a charm and now pass is finally a platform independent password safe alternative that is actually usable! 
Good work! Thanks!

**Comment by CodogoFreddie** [comment]
I'm still experiencing this error even after doing a full re-install, are there any other possible causes?

**Comment by maximbaz** [comment]
Did it work before 2.0.0? Could you confirm that [v1.0.15](https://github.com/dannyvankooten/browserpass/releases/tag/1.0.15) works for you? Does it work when you start browser from terminal? The most common issue that I'm aware is #13. What is your browser & OS?

**Comment by CodogoFreddie** [comment]
I'm on Linux
I was previously using `1.0.5` on chrome, and tried upgrading to `2.0.2` on firefox.

I've downgraded firefox to `1.0.5` and it's now working again, I'll probably try upgrading both later when I can spend some time properly getting into it.

Thank you :)
 
(starting from the terminal didn't help)

**Comment by maximbaz** [comment]
@CodogoFreddie your issue is probably the same as in #172.
