### ISSUE TITLE
Recognizing login pages on alternate domains

### ISSUE THREAD

**Issue by tanderson92** [dannyvankooten/browserpass#167]
Per Maxim's [comment](https://github.com/dannyvankooten/browserpass/issues/117#issuecomment-333300447) in #117, one issue that I've seen is sites which have alternate domain names

Is there any way to add support for a tag (similar to the username one) in the password files to recognize other domain names? The example I have in mind is merrilledge.com but links are sent to clients with the "os.ml.com" (for merrill lynch the parent company) domain. Any thoughts on if this is feasible? Sorry if this has been raised elsewhere.

**Comment by maximbaz** [comment]
I explained [here](https://github.com/dannyvankooten/browserpass/issues/93#issuecomment-330363450) why adding tag is not a good idea. The recommended way is to create a symlink called "os.ml.com.gpg" pointing to a real file called "merrilledge.com.gpg". Browserpass will pick it up!

Symlinking directories however is unfortunately not supported yet, we are tracking this in #85.

I'll close this, but let me know if you have some further questions about this.
