### ISSUE TITLE
wiki.archlinux autofill problem

### ISSUE THREAD

**Issue by duffydack** [dannyvankooten/browserpass#168]
archlinux x86_64 and chromium Version 61.0.3163.100
aur.archlinux, bbs.archlinux both autofill both fields and login, but wiki.archlinux asks me to fill in username field.  My password store is using the correct schema
password
login: mylogin

![1](https://user-images.githubusercontent.com/20307378/31049299-5fe9fc34-a628-11e7-8a59-810dda1a1b59.png)

It is slightly different to the rest of the login forms for *.archlinux.  Thoughts?

**Comment by maximbaz** [comment]
Thanks, another useful example, the fix will be part of 2.0.2 :+1:

**Comment by duffydack** [comment]
What is it exactly, for curiosity sake?

**Comment by maximbaz** [comment]
See the commit, it's one liner: https://github.com/dannyvankooten/browserpass/commit/bb7cd0c41ce954ef09061a1efd7586a6f1082762

Basically previously we've been matching by field ID only, but archwiki uses class names. We do have fallback mechanisms (like if no login field is found, try the first text field in the form), but unfortunately archwiki doesn't define input type to be text, so even fallback mechanism didn't work. Luckily they at least use good class names for the field, and that's what I added for matching now.
