### ISSUE TITLE
[Regression] Dialoag no longer waits on yubi touch input

### ISSUE THREAD

**Issue by benjumanji** [dannyvankooten/browserpass#170]
Older versions of the extension used to wait until the gpg would actually do the decrypt, now the dialog closes instantly and I forget sometimes that I still need to touch the device for my password to be filled out.

### General information

* Operating system + version: Arch Linux
* Browser + version: Firefox 56
* If installed an official release, put a release version: 2.0.0
* If built from sources, put a commit id (`$ git describe --always`): 
* Browserpass extension version as reported by your browser: 2.0.3

---

### Exact steps to reproduce the problem
1. Use a yubikey with touch to decrypt enabled
2. Attempt to use any password

### What should happen?

Spinny gif until yubi is touched, then dialog closes

### What happened instead?

Dialog closes immediately

**Comment by benjumanji** [comment]
Thanks!

**Comment by maximbaz** [comment]
Thank you for the hint with "touch to decrypt", I've somehow missed this possibility when I was configuring my Yubikey - I like it 👍  

I'll update webstores with a new release now, so you can also enjoy this spinning circle while waiting for the touch 😃
