### ISSUE TITLE
Error: Access to the specified native messaging host is forbidden.

### ISSUE THREAD

**Issue by eiso** [dannyvankooten/browserpass#172]
### General information

* Operating system + version: Arch Linux (Kernel version: 4.11.9-1)
* Browser + version: Version 61.0.3163.91 (Official Build) (64-bit)
* If installed an official release, put a release version: aur/browserpass 2.0.4-1 [installed] 
* If built from sources, put a commit id (`$ git describe --always`): 
* Browserpass extension version as reported by your browser: 2.0.4

---

### Exact steps to reproduce the problem
1. Click on the lock icon in the browser

### What should happen?

Show the list of accounts

### What happened instead?

`Error: Access to the specified native messaging host is forbidden.`

### Extra

This happened after upgrading from a 1.x version.

**Comment by maximbaz** [comment]
This is probably not it, but just in case, could you double-check that you don't accidentally have two browserpass chrome extensions installed? There should only be "browserpass-ce", with a blue icon. 

The error message itself suggests that you have an issue with the native messaging host definition. How many entries does this command find, and please post the contents of each of them:

```
$ locate com.dannyvankooten.browserpass.json
```

**Comment by eiso** [comment]
No two installations and ID of the extension matches. 

Here is the locate output (obfuscated is the username of the system):

```locate com.dannyvankooten.browserpass.json
/etc/chromium/native-messaging-hosts/com.dannyvankooten.browserpass.json
/etc/chromium/policies/managed/com.dannyvankooten.browserpass.json
/etc/opt/chrome/native-messaging-hosts/com.dannyvankooten.browserpass.json
/etc/opt/chrome/policies/managed/com.dannyvankooten.browserpass.json
/home/obfuscated/.config/google-chrome/NativeMessagingHosts/com.dannyvankooten.browserpass.json
/home/obfuscated/.config/google-chrome/policies/managed/com.dannyvankooten.browserpass.json
/usr/lib/mozilla/native-messaging-hosts/com.dannyvankooten.browserpass.json
```

**Comment by maximbaz** [comment]
I bet one of these files is a left-over from v1, which is incompatible with v2. Simple idea: just try to remove all of them and install aur/browserpass again. Except, the last file is for Firefox though, maybe keep it if you use Firefox, I don't think browserpass handles it.

**Comment by eiso** [comment]
That solved it. Thank you very much for the **very fast help!**

**Comment by eiso** [comment]
p.s. A big thank you for maintaining this project. I am a very happy and grateful user.

**Comment by maximbaz** [comment]
Happy to hear it! 🙂
