### ISSUE TITLE
Auto-fill not working on reddit.com

### ISSUE THREAD

**Issue by zsau** [dannyvankooten/browserpass#174]
browserpass-ce 2.0.4 on FF 56.0 / Mac

Auto-fill gets bamboozled into filling out the "Create a new account" form on the left side of https://www.reddit.com/login, instead of the actual login form on the right.

**Comment by maximbaz** [comment]
This was a good report, when multiple forms are visible at once, browserpass was naively picking the first one. I added some logic that attempts to detect which one is a login form. If such detection fails, the code will fallback to use the first visible form.

This fixes reddit.com, if there are other examples where a wrong form is still being filled out, please submit the websites here.
