### ISSUE TITLE
Auto submit doesn't work on forum.osdev.org

### ISSUE THREAD

**Issue by chrboe** [dannyvankooten/browserpass#176]
### General information

* Operating system + version: Gentoo Linux
* Browser + version: Chromium 61.0.3163.100
* If installed an official release, put a release version: -
* If built from sources, put a commit id (`$ git describe --always`): `a255534`
* Browserpass extension version as reported by your browser: 2.0.4

---

### Exact steps to reproduce the problem
1. Navigate to http://forum.osdev.org/ucp.php?mode=login
2. Let browserpass autofill the form

### What should happen?

The form should get submitted

### What happened instead?

Username and password get filled, but the form isn't submitted

### Extra

I suspect this is a general phpBB problem

**Comment by maximbaz** [comment]
Their markup is correct, but our heuristic detected the "Login" button as a trap for spammers, because the button is unusually narrow 😄 I added that heuristic some time ago because I saw a real example of it.

See commit above for details 🙂
