### ISSUE TITLE
Ctrl+Shift+L shortcut not working in FF or FF Nightly

### ISSUE THREAD

**Issue by juicetin** [dannyvankooten/browserpass#185]
### General information

Bug report as per my issue highlighted briefly on the Add-ons page - https://addons.mozilla.org/en-US/firefox/addon/browserpass-ce/reviews/939821/

* Operating system + version: Arch Linux, x86_64 Linux 4.13.9-1-ARCH
* Browser + version: Firefox 56.0.2-1 and Firefox Nightly 58.0a
* If installed an official release, put a release version:  56.0.2-1/58.0a1
* If built from sources, put a commit id (`$ git describe --always`): N/A
* Browserpass extension version as reported by your browser: 2.0.6

---

### Exact steps to reproduce the problem
1. Install the browserpass-ce addon from the Firefox Add-ons list in either latest stable Firefox *or* latest Firefox Nightly
2. Attempt to use Ctrl+Shift+L shortcut (the shortcut doesn't come up)

### What should happen?
The browserpass extension matched URL password list should appear

### What happened instead?
Nothing happens

**Comment by maximbaz** [comment]
Hey, thanks for reporting the browser versions! Could you also tell me what is your OS and what keyboard layout you have?

**Comment by juicetin** [comment]
Hey! My bad, forgot to include the OS line, updated my original issue with that detail:
OS - Arch Linux, x86_64 Linux 4.13.9-1-ARCH.

The output of `localectl status` for me is 
`   System Locale: LANG=en_AU.UTF-8
       VC Keymap: n/a
      X11 Layout: n/a
`

**Comment by maximbaz** [comment]
What desktop environment do you have? Could it be that there is already registered a hotkey <kbd>Ctrl+Shift+L</kbd> on your system for something completely different? It would also be cool if you could try on Chrome/Chromium to see if the issue is with Firefox browsers or with all browsers (the latter would probably indicate that something on OS level is stealing the keypress).

**Comment by juicetin** [comment]
Ah, yeah I was trying to use it on Chrome a little while back as well with no luck - so it's probably something in the system stealing the shortcut.

I'm running i3-gaps, and yep, totally overlooked the fact that Ctrl+Shift+L is currently reserved already for adjusting window splits.

and the output I get when pressing those 3 keys is:
```
KeyPress event, serial 28, synthetic NO, window 0x3c00001,
    root 0x16e, subw 0x0, time 40039667, (473,725), root:(2377,1860),
    state 0x0, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0x3c00001,
    root 0x16e, subw 0x0, time 40039680, (473,725), root:(2377,1860),
    state 0x1, keycode 66 (keysym 0xffe3, Control_L), same_screen YES,
    XKeysymToKeycode returns keycode: 37
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

The old version installed from command line had the shortcut Alt+Shift+L which worked for me - is there any chance we could get an option to toggle between the two, or be able to set an arbitrary shortcut in the addon's setttings?

**Comment by maximbaz** [comment]
The "default" shortcut is defined in manifest:

https://github.com/dannyvankooten/browserpass/blob/20b6dd1c99241fdd848211d6cf3aec1d6144038b/firefox/manifest.json#L33

Unfortunately Firefox does not support changing this default (Chrome does), and the old shortcut was causing so many troubles that we had to come up with a better default. The discussion was happening in #160, have a look. 

I'm not sure if there is an open bug for Firefox to add a way to configure the shortcut, if you want you can try to search and maybe report the issue - if you do, please post the link here for others to find.

Other than that, I'm afraid I don't think I can help much.

**Comment by juicetin** [comment]
Ah fair enough - my easiest temporary/semi-permanent solution is probably to just sideload an extension with a different default shortcut then - could you point me in the right direction to be able to do that from your repo?

**Comment by maximbaz** [comment]
You should know that there is another inconvenience with Firefox, it removes all sideloaded extensions once the browser is closed. It is quite annoying to reload it every time you start a browser. Maybe another workaround would be to change the hotkey for adjusting window splits?

Anyway, for sideloading there are two options:
- Clone the repo and follow [CONTRIBUTING.md](https://github.com/dannyvankooten/browserpass/blob/master/CONTRIBUTING.md), it describes which dependencies you need, how to compile backend and frontend.
- Download `firefox.zip` from the latest release, it has already compiled code of the firefox extension.

Once you do either of that, adjust the shortcut here:

https://github.com/dannyvankooten/browserpass/blob/20b6dd1c99241fdd848211d6cf3aec1d6144038b/firefox/manifest.json#L33

And load the extension in Firefox as described [in this section](https://github.com/dannyvankooten/browserpass/blob/master/CONTRIBUTING.md#to-load-an-unpacked-extension).

**Comment by maximbaz** [comment]
Let me know if there is something else I could help with.
