### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by christian-karlsson** [dannyvankooten/browserpass#186]
### General information

* Manjaro 17.0.6
* Chrome version 61.0.3163.100
* Firefox version 56.0.2
* installed thru git clone https://github.com/dannyvankooten/browserpass
* If built from sources, put a commit id (`$ git describe --always`): 
* Browserpass extension version as reported by your browser:

---

### Exact steps to reproduce the problem
1. sudo ./install.sh
2. Select your browser (choosing Firefox)
3.

### What happened instead?
when im choosing firefox this happened:
browserpass/firefox-host.json is missing

choosing chrome:
browserpass/chrome-host.json or browserpass/chrome-policy.json is missing.

**Comment by maximbaz** [comment]
Hi, running `sudo ./install.sh` is only enough if you downloaded `browserpass-src.tar.gz`, which already contains all dependencies.

If you cloned repo, you have to fetch all dependencies first and compile frontend and backend code before you can install the app. Please follow [CONTRIBUTING.md](https://github.com/dannyvankooten/browserpass/blob/master/CONTRIBUTING.md) for details, and let me know if something is not clear there.
