### ISSUE TITLE
"Error: An unexpected error occurred" on Mozilla firefox Nightly

### ISSUE THREAD

**Issue by naman** [dannyvankooten/browserpass#191]
### General information

* Operating system + version: macOS High Sierra v10.13.1
* Browser + version: Mozilla Nightly, 59.0a1 (2017-11-21) (64-bit)
* If installed an official release, put a release version: [v2.0.7](https://github.com/dannyvankooten/browserpass/releases/tag/2.0.7)
* If built from sources, put a commit id (`$ git describe --always`):  NA
* Browserpass extension version as reported by your browser: v2.0.7

---

### Exact steps to reproduce the problem
1. Install browserpass-ce firefox extension
2. Install browserpass via `./install.sh`; run the browserpass binary
3. Clicked on browserpass padlock icon on Firefox, gives an error "Error: An unexpected error occurred"

![screen shot 2017-11-22 at 12 33 35 pm](https://user-images.githubusercontent.com/5255299/33114610-8f0bc4be-cf83-11e7-8c71-92d8884a8890.png)

### What should happen?
Atleast a verbose error message telling what to debug, and what went wrong.

### What happened instead?
The error message is not really helpful.

**Comment by maximbaz** [comment]
Totally agree on the meaningful error messages, we are tracking that with #164.

Shall we try to debug your particular issue? I'm not very familiar with Firefox, but I just found the page about:debugging#addons and there is a "Debug" link under every extension - does it print any helpful message in there?

I could also suggest to try in Chrome, just to see if the issue is browser-specific or not. In Chrome I know how you can debug front-end (right-click on the extension icon and select "Inspect pop-up") and backend (go to chrome://extensions/ and click "Inspect view: background page)

Let me know how it goes.

**Comment by maximbaz** [comment]
I'll close this as duplicate of #164, but do let me know if you need some help debugging the installation, I'd be happy to help.

**Comment by naman** [comment]
I tried this on Firefox, just to make sure it wasn't a Nightly issue, and got the same issues. I did try to debug using the instructions you've given. The following screenshot might help
<img width="891" alt="screen shot 2017-11-26 at 1 33 33 am" src="https://user-images.githubusercontent.com/5255299/33234277-ef2f962c-d249-11e7-91d2-4570e20ff887.png">

**Comment by maximbaz** [comment]
This message "unexpected error occurred" is not part of our code, my best guess is that Firefox has troubles communicating with the host app. There are still many ways where it could be wrong, do try in Chrome to see if this is browser specific or not.

By the way, I see you are on Mac, just today there was submitted a homebrew formula for this extension,  it's not merged yet, but maybe you could try it?

https://github.com/Homebrew/homebrew-core/pull/21039

**Comment by naman** [comment]
Yep, looks like Firefox has issues with connecting the host app. I installed using the forementioned brew formula and installed Native Messaging host config for both firefox and Chromium.

Firefox still shows: Error: An unexpected error occurred
Chromium: Error: Native host has exited.

**Comment by maximbaz** [comment]
OK, so this is not browser-specific then. It is likely not an issue with the configs, since you tried two methods and both failed. Could you check that the host application works correctly for you? There is this nice script that is useful for this purpose: https://github.com/chrboe/native.pl

**Comment by maximbaz** [comment]
Actually, now I'm recalling that GPGTools needed on Mac to make it work. See this comment and below: https://github.com/dannyvankooten/browserpass/issues/13#issuecomment-332735747

Could you confirm that you have it, or install if not?

**Comment by naman** [comment]
Yes, I have GPGTools installed already. I also tried running the native.pl and this is the output
 
bash-4.4$ ./native.pl browserpass {\"action\": \"search\", \"domain\": \"github.com\"}
Request: |  {"action":"search","domain":"github.com"} 
Result:  |  []
Errors:  |  -

**Comment by maximbaz** [comment]
Alright (it wouldn't hurt to ensure this dependency in homebrew formula nonetheless). Can you try with a different domain that you definitely have in your password store to make sure it returns some result? If you see some non-empty result, it is likely something related to communication between browser and host app, I'll get back to you with some ideas a bit later

**Comment by naman** [comment]
I see. Yes, it returns a correct (non-empty) result. (y)

**Comment by maximbaz** [comment]
Check the contents of these files (if they exist):

1. "/Library/Application Support/Mozilla/NativeMessagingHosts/com.dannyvankooten.browserpass.json"
2. "$HOME/Library/Application Support/Mozilla/NativeMessagingHosts/com.dannyvankooten.browserpass.json"

At least one of them must exist.

In those files there is `"path"` parameter, it must have full path to the host binary file that you downloaded (or installed via homebrew). Check if the path is correct and the file exists.

Besides all of the above, try starting browser from the terminal (and not from application launcher) and see if the issue persists.

Let me know how this goes.

**Comment by naman** [comment]
Yes, the `path` parameter points to the correct location of browserpass binary in both `"$HOME/Library/Application Support/Mozilla/NativeMessagingHosts/com.dannyvankooten.browserpass.json"` and `"$HOME/Library/Application Support/Chromium/NativeMessagingHosts/com.dannyvankooten.browserpass.json"`. Also, a suggestion would be to run browserpass (homebrew version) as a service using [brew services ](https://github.com/Homebrew/homebrew-services) (which makes use of launchctl)

**Comment by maximbaz** [comment]
Users don't need to launch the host app, users only need to put the host app somewhere and create proper configs. It is browser who is launching the host app. So there is no need for a service (if I correctly understood its purpose).

**Comment by naman** [comment]
Ah, okay. I got it confused. Makes sense.

**Comment by maximbaz** [comment]
I'm running out of ideas 😄 Can you try to browser from terminal and not from application launcher?

**Comment by naman** [comment]
wow, it worked. Although, I am not sure I understand why. I tried `open /Applications/Firefox.app` and the extension works good. Thanks for taking time to debug 👍

**Comment by maximbaz** [comment]
We had this issue, almost everyone on Mac was affected, but I solved it with #159 (or so I thought, but everyone confirmed the fix).

Could you please paste the output of these commands?

```
$ which gpg
$ which gpg2
```

**Comment by naman** [comment]
Here you go!

```
⋊> ~ which gpg                                                                                  
/usr/local/bin/gpg
⋊> ~ which gpg2                                                                                 
/usr/local/MacGPG2/bin/gpg2
```

**Comment by maximbaz** [comment]
Could you please try the attached binary (replace what you have), does it solve the issue when browser is started as usual (not from terminal)?

[browserpass-darwinx64.zip](https://github.com/dannyvankooten/browserpass/files/1503447/browserpass-darwinx64.zip)

**Comment by naman** [comment]
Doesn't solve the issue.

**Comment by maximbaz** [comment]
Ok, thanks... I'm not sure what causes this and how to fix it, I'm definitely going to keep an eye on this and see if anyone else reports this. 

In meantime, you can check the issue #13, when this was a common problem people came up with multiple ways to create wrappers, which allowed to use launcher to start the browser (like [this](https://github.com/dannyvankooten/browserpass/issues/13#issuecomment-332198952)), maybe some of them will work for you too.

**Comment by jwiegley** [comment]
Hi @maximbaz, I just upgraded from 57.0.1 to 57.0.2 today, and I started getting this same error as well, with really no idea of how to address it.

I deleted Firefox, reinstalled it. Then downloaded the browserpass binary and reinstalled it. In 57.0.1 browserpass worked fine, but now I'm getting "An unexpected error occurred".

Any hints on how to figure out what broke?

**Comment by jwiegley** [comment]
Strangely, it just started working again, but I don't know why.

**Comment by maximbaz** [comment]
Hey, not sure if you managed to resolve it or not (I received an email that you did 😃), if not - try to collect answers to the questions I was asking above, maybe some of them will differ and help indicating what could be the issue... Honestly this is the weirdest issue of all 😕

**Comment by jwiegley** [comment]
@maximbaz Hi Maxim, the problem did indeed go away, but then I switched to installing `browserpass` via Nix (and changed the `.json` file to point to it), but then it came back. However, right now it appears to be working. So I'd love to figure out *why* it fails, so that I can track down how to prevent it from being in a failing state again. Some logging in the binary to see if it's even being called, and how far it gets, might help...

**Comment by maximbaz** [comment]
Indeed. This will come in #164 if someone is brave enough to start working on it. Good idea about introducing logging for the host app, I added it to the description of that ticket.
