### ISSUE TITLE
Running on Windows through WSL

### ISSUE THREAD

**Issue by jtsymon** [dannyvankooten/browserpass#192]
[This setup probably isn't worth supporting, I'm just leaving this here as a guide for anyone else with a similar setup]

I use browserpass on Linux, and occasionally have to use Windows, so I was pleased to find browserpass supports Windows... except I already use pass under WSL, which the Windows host doesn't work with. So I figured instead of setting up a second copy of my password store for the Windows host, I would just make browserpass go through WSL. Turns out to be quite simple:

1. Install the Windows host application, as well as the Linux host application (under WSL).
2. Create `%localappdata%\browserpass\browserpass-linux.bat` with the following contents:
```
@echo off
bash -c ~/browserpass/browserpass-linux64
```
3. Change the path in `%localappdata%\browserpass\browserpass-firefox.json` (or `-chrome.json`) to point to `browserpass-linux.bat`

Now the browser extension should be able to load password entries, but if you have a password on your GPG key it will probably fail to decrypt passwords due to the key not being loaded in your gpg-agent. Normally on Linux gpg-agent would just pop up a password input, but this doesn't work with WSL (maybe it is possible if you install X11 under WSL?)
Anyway, you can work around this by loading the GPG key into your gpg-agent inside WSL (e.g. just load a password inside WSL). Kind of annoying, but it works.

**Comment by maximbaz** [comment]
Hey, thanks for sharing! I think these instructions are useful, but it would be difficult to find them among issues (I'd also like to keep only actionable issues open). Would you consider opening a PR and adding maybe a condensed description of this to the README.md? I suggest adding this to Installation section, perhaps as a new subsection "Installing the host application on Windows through WSL" after the subsection "Installing the host application".

**Comment by frebib** [comment]
I'd like to add that this can be fully automated with a self-starting gpg-agent and Windows-invoked graphical password entry, similar to standard `pinentry` applications.

I managed to get this working with a combination of [https://github.com/diablodale/pinentry-wsl-ps1](pinentry-wsl-ps1) which uses Powershell and several hours of pulling my hair out. I have some reasonably complex bash and zsh configuration so this may need tweaking to work for everyone but here is roughly what I did:

- Download and locate the `pinentry-wsl-ps1` script (I put it in `/usr/local/bin/pinentry-wsl`)
- Configure `gpg-agent` to use the above pinentry application:
  - ```diff
     ~/.gnupg/gpg-agent.conf
     ------------------------------
    +pinentry-program /usr/local/bin/pinentry-wsl
    ```
- I had to change `%localappdata%\browserpass\browserpass-linux.bat` to `cd` to my home directory:
  - ```diff
     @echo off
    -bash -c ~/browserpass/browserpass-linux64
    +bash -c 'cd /home/frebib; ~/browserpass/browserpass-linux64'
    ```

If anyone wants to try this, I am happy to help them debug and attempt to get it working. When we work out a consistent method of getting it working I can open a PR with some documentation for the README

**Comment by kpengboy** [comment]
@frebib I've been able to get it to work using pinentry-wsl-ps1 too. I put the script in `~/opt/pinentry-wsl-ps1.sh` instead, and also did not need to change anything in `%localappdata%\browserpass\browserpass-linux.bat`.

**Comment by maximbaz** [comment]
I have included your additions in the README of Browserpass v3: 

https://github.com/browserpass/browserpass-native#install-on-windows-through-wsl
https://github.com/browserpass/browserpass-native#hints-for-configuring-gpg

By the way, if you have time, please test it and share your feedback in https://github.com/browserpass/browserpass/issues/331
