### ISSUE TITLE
Idea: align host app with gopass jsonapi, make extension support both host apps

### ISSUE THREAD

**Issue by maximbaz** [dannyvankooten/browserpass#194]
Hey @martinhoefling, I've seen you implemented native messaging support for `gopass`, as well as your work on `gopassbridge`. First of all - nice job!

This got me thinking: instead of maintaining two separate projects that essentially do the same thing, how difficult would it be possible to join forces?

I noticed that while the browser extension part in this project is being changed and improved often, the host app changes much more rarely.

I didn't dig much into the native messaging part of `gopass` yet, but I imagine it works pretty much similar to browserpass, communicating JSON back and forth, requesting domain and returning credentials back.

We could maybe make the API of the `browserpass` host app compatible with `gopass` API (basically align JSON structure, I think), and thus make the browser extension work with any host app, `browserpass` or `gopass`. 

I think more and more people will be switching to `gopass` over time, having a feature rich browser extension that supports both `gopass` and older `pass` via `browserpass` host app would be very beneficial.

People who use `gopass` would not require the backend part of this project, they would only need the browser extensions. People who continue using `pass` would need to install both native host app as well as a browser extension.

I'd even want to split the project into two, one hosting a browser extension and another hosting the native host app.

What are your thoughts? What would be the challenges, difficulties? Is it even feasible?

Everyone else is of course welcome to add your input!

**Comment by erayd** [comment]
I don't mind either way, so long as support for `pass` doesn't go away. Adding `gopass` support does seem like something that would be useful, and unification of the API makes sense.

**Comment by maximbaz** [comment]
Closing due to lack of interest.
