### ISSUE TITLE
OTP next steps

### ISSUE THREAD

**Issue by ashkitten** [dannyvankooten/browserpass#195]
Back in October I implemented a better method of displaying OTP codes (#179). I suppose the next obvious step would be to implement a way to refresh the OTP code after it expires, but I'd also like to hear feedback about the current implementation and see how we can improve it?

**Comment by maximbaz** [comment]
Great initiative! I personally don't use this feature, /cc @qbit who might have some feedback.

**Comment by qbit** [comment]
I thought about this for a while - Refresh would likely have to be one of:

- re-query the entire entry
- pass the secret to the browser (not really an option imo)

I think the best way would be to pass a time value alone with the digits.. the JS in the browser then parses the time and displays a countdown / re-queries after that. Feels dirty passing the password multiple times though - maybe that bit could easily be separated out?

**Comment by maximbaz** [comment]
Re-querying the entry seems like a reasonable approach.

I'd suggest to wait with separating out OTP from login data for now, I want to see if there is anyone interested in aligning backend api to `gopass` (see #194) - in that case backend will change and such separation could be a wasted effort.

Is this time value something that is being generated by the golang library that we use for OTP? We can't just assume that we always have 30 seconds for a given OTP code, can we?

**Comment by qbit** [comment]
It's fairly easy to generate (There is a countdown bar in gopass): https://github.com/justwatchcom/gopass/blob/master/action/otp.go#L71-L81

That said - I have implemented it enough now that I feel it should be in the twofactor lib ;D

**Comment by maximbaz** [comment]
#194 does not have any interest, so if you want to proceed on implementing this - please go ahead and open a PR.

However this topic didn't have much attention too during the past two months, either everyone is happy with the current implementation of OTP, or nobody is using it besides you two 🙂
