### ISSUE TITLE
Filter the list of already discovered passwords

### ISSUE THREAD

**Issue by maximbaz** [dannyvankooten/browserpass#211]
I open `github.com`, click on browserpass and see two results: `github.com/work` and `github.com/personal`. I'd like to filter this list down, type `wo` and leave only `github.com/work` in place. However by doing this I don't want to add `wordpress.com` to the list, I'm not _searching_, I'm _filtering_ passwords here.

These are the initial requirements that I came up with, feel free to comment/suggest:
- The filtering should be fuzzy and only fuzzy, so I can type `wk` and it will also find `github.com/work`. It doesn't make sense to support grep or glob, the list being filtered is likely small, so there is no concern to "find too many results".
- The filtering should be done on javascript side, no need to make calls to backed, we already have all info we need.
- I think the same search bar can be reused for search and filtering, I'm thinking about some having a toggle for modes. The default behavior can be like that:
    - If browserpass is opened and there are no matches, the mode is "search".
    - If browserpass is opened and there are results, the mode is "filter".
    - There needs to be some kind of button/icon next to the search bar to toggle the mode.
    - Placeholder can reflect the current mode, now it says "Search password...", can also say "Filter passwords...".
- The filtering should be in real time, I type `w` and the list is immediately being filtered, no pressing "Enter". If there is only one result left, pressing "Enter" should select it (this will also fix #40).

**Comment by sophacles** [comment]
The filter/search differentiation and cancelling filter to return to search can be handled like this:
 (reusing your example above)
* When there is a domain match, the domain can be displayed in the search box, with the url text highlighted having a background color. (and maybe other fancy decorations :) ).
* when the user types in the search box, it fuzzy filters in the domain results.
* If there is no user-entered text in the search box (so just the highlighted domain name), and the user presses backspace, search mode reverts from filter to full search, and text put into the search bar runs through full search.

**Comment by sophacles** [comment]
Regarding:

> The filtering should be in real time, I type w and the list is immediately being filtered, no pressing "Enter". If there is only one result left, pressing "Enter" should select it (this will also fix #40).

Can the keypress handler also be used for normal search to do real-time search as well (based on filter/search mode setting)?  I know that's a different ticket probably, but bringing it up here as it may influence how the code for filter is designed.

**Comment by maximbaz** [comment]
I like the idea of how you describe filter/search, it reminds me of how Chromium draws search bar for custom searches:

![filter](https://user-images.githubusercontent.com/1177900/36048923-2992cde8-0de1-11e8-80c6-8176c30d2d39.gif)

> Can the keypress handler also be used for normal search to do real-time search as well?

I tried that at some point, it sounds cool but in reality it was a weird experience, I have hundreds of passwords and typing one letter changes the results list in a very unexpected way, especially when you press Backspace and the list suddenly grows with 20 new records, or when you clear the search box to type a completely new domain and the list fills up with all of your 100 passwords...

Filtering on keypress makes sense, because you are filtering a very limited subset of records and no unusual matches ever popup, but after that experiment I believe searching on keypress is too weird.

**Comment by sophacles** [comment]
Oh nice gif! That's exactly what I was describing - I didn't realize it was from Chromium, just knew it was a pattern I've encountered before that works here :).

Re real-time search - that makes sense.
