### ISSUE TITLE
Add a button to open entry in a new tab (and use `url` field if it exists)

### ISSUE THREAD

**Issue by petr-nehez** [dannyvankooten/browserpass#214]
### General information
Would it be possible to add a feature to read `url` field?
I liked this in LastPass where you just search through your items, click it and the browser opens your stored URL.

* Operating system + version: Manjaro KDE
* Browser + version: Waterfox 56.0.4.1
* Browserpass extension version as reported by your browser: 2.0.11

**Comment by braderhart** [comment]
Agreed, but foldername as URL for now may help keep it simple.

**Comment by petr-nehez** [comment]
Well, I do not think foldername is the best place for URL.
I have many folders but none of them contains any URL (even not the part of it).
Then e.g. I have an item `gitlab.com` but the content of its `url` field is **https://gitlab.com/users/sign_in**.

**Comment by braderhart** [comment]
Not saying it isn't possible, but easier to implement as a starting point
with some functionality so that you can then use that to decrypt the
relevant password file(s).

**Comment by maximbaz** [comment]
Just to clarify, how do you want it to look like? Today clicking on the entry fills in the form, so is it going to be a new button next to "copy username" and "copy password"? Supporting a `url` field in this case is totally acceptable, with a fallback to the file name or folder name with the domain.

**Comment by petr-nehez** [comment]
> a new button next to "copy username" and "copy password"?

Yes, ideally :+1:

**Comment by maximbaz** [comment]
This will also solve #103 by the way, at least in Chromium.

Just to make it clear, if we parse `url` field, it will only be used to _open_ links with this new button, not for automatic domain matching - see #93 for more details on that.

**Comment by petr-nehez** [comment]
> it will only be used to open links with this new button, not for automatic domain matching

That's understandable and I even didn't think about it.

**Comment by maximbaz** [comment]
Released in v2.0.14, kudos to @erayd for implementing this!

**Comment by petr-nehez** [comment]
Perfect, thanks @erayd!
