### ISSUE TITLE
Show notification with major news/changes on browser extension auto-update

### ISSUE THREAD

**Issue by maximbaz** [dannyvankooten/browserpass#219]
When browser extension auto-updates, I'd like it to optionally display a browser notification with a custom message. 

This will be useful for letting people know when it is required to update host app (e.g. #218) or any other major changes. This will be much better communication channel than a github issue.

I don't need to show the notification every time, for example when there is no change to host app.

**Comment by jangari** [comment]
I concur. I just spent an hour trying to find out why the native host had exited. The behaviour appeared _opposite_ to the typical warning (no pinentry, bad gpg/2 path) in that it allowed me to search the password store and enter my passphrase, but would not auto detect from the url.

**Comment by maximbaz** [comment]
Gonna be part of the 2.0.13 that I just published on both webstores, it will show notification so hopefully those that are updating from 2.0.11 straight to 2.0.13 will not waste time investigating what's wrong with their password store.

![image](https://user-images.githubusercontent.com/1177900/37611195-fcb8b024-2ba1-11e8-8614-36300659fed6.png)

**Comment by lwm** [comment]
Thanks @maximbaz, that is really great.
