### ISSUE TITLE
browserpass-ce 2.0.13 - Error: An unexpected error occurred

### ISSUE THREAD

**Issue by KarlFiabeschi** [dannyvankooten/browserpass#222]
### General information

* Operating system + version:
Arch Linux
* Browser + version:
Firefox 59
* If installed an official release, put a release version: 
browserpass-ce 2.0.13
* Browserpass extension version as reported by your browser:
browserpass-ce 2.0.13
---

### Exact steps to reproduce the problem
1. Updated to last version

### What should happen?
Work as always 

### What happened instead?
Error: An unexpected error occurred

pls describe how i can debug more the problem

**Comment by maximbaz** [comment]
Can you confirm that the host app has version v2.0.13? How did you install it by the way, via AUR?

**Comment by KarlFiabeschi** [comment]
yep, as you pointed the problem was on the host app.
Updated, all work as expected .

thanks for your work
