### ISSUE TITLE
Fuzzy searching appears broken.

### ISSUE THREAD

**Issue by blovett** [dannyvankooten/browserpass#225]
### General information

* MacOS 10.13.3
* Firefox 60.0b5
* 2.0.11 (but still seen with host application 2.0.13)
* Information about the browser extension:
  * Browserpass extension version as reported by your browser: 2.0.13

---

### Exact steps to reproduce the problem
1. Have fuzzy searching enabled.
2. Attempt to lookup a password for a site.

### What should happen?

The password entry should be found.

### What happened instead?

The message "Error: undefined" is returned.

Through git bisect, I found this commit is the first one where the issue crops up: 30c9da4572c6e7c6789a4b3ac5bf7d36dd7210fc. However, unchecking the option to enable fuzzy search doesn't appear to help the issue, so it may be something else more involved.

**Comment by maximbaz** [comment]
When you say "still seen with host app 2.0.13", can you confirm that browser is also using v2.0.13 and not the older one (in case you haven't removed it)? The current browser extension does not work with host apps older than 2.0.12, so you can remove the 2.0.11 for good and upgrade to the latest version.

**Comment by blovett** [comment]
Yeah, it should be the 2.0.13 host app.

```~ % sha256 /Users/blovett/.browserpass/browserpass-darwinx64
SHA256(/Users/blovett/.browserpass/browserpass-darwinx64)= cca9d8a3c28dc5915422f344fd575748e38b2300d0ba4643a88765fa17260c31
~ % cat ~/Library/Application\ Support/Mozilla/NativeMessagingHosts/com.dannyvankooten.browserpass.json
{
  "name": "com.dannyvankooten.browserpass",
  "description": "Browserpass binary for the Firefox extension",
  "path": "/Users/blovett/.browserpass/browserpass-darwinx64",
  "type": "stdio",
  "allowed_extensions": [
    "browserpass@maximbaz.com"
  ]
}```

**Comment by blovett** [comment]
Shoot. I just verified again (fresh download), and sha256 *is* different. I'm sorry for the confusion. I re-copied the app over, and all is good.
