### ISSUE TITLE
Popup view correct?

### ISSUE THREAD

**Issue by petr-nehez** [dannyvankooten/browserpass#234]
### General information

* Operating system + version: Manjaro KDE
* Browser + version: Chromium 64
* Information about the host app: 2.0.15
* Information about the browser extension: 64.0.3282.186
  * Browserpass extension version as reported by your browser: 2.0.16

---

![image](https://user-images.githubusercontent.com/1265990/37817992-ec7a49d2-2e78-11e8-9c4c-9abd04a80f4e.png)

Is this wrapping correct?

**Comment by maximbaz** [comment]
Thanks - no, shouldn't be like that. I'll disable wrapping.

**Comment by petr-nehez** [comment]
Thanks :+1:
