### ISSUE TITLE
print version of host app

### ISSUE THREAD

**Issue by Ennoia11** [dannyvankooten/browserpass#238]
* OS + version : linux 64 bit + archlinux up-to-date kernel 4.15.11 gcc 7.3.1
* Browser + version : chromium 65.0.3325.181
* Information about the host app:
  * If installed via package manager or downloaded from [releases](https://github.com/dannyvankooten/browserpass/releases) page, put a version:  
downloaded from github version ???
* Information about the browser extension : chromium auto update 2.0.17
  * Browserpass extension version as reported by your browser: 2.0.17
---
I ran into some problems (don't remember the exact message) so I've check the version
browser extension : 2.0.17
host app : unable to determine
so I downloaded the corresponding version of the host app and everything felt in line.

What should appended ?
typing browserpass-linux64 -v should print the version of the host app

**Comment by maximbaz** [comment]
Good idea, implemented 👍
