### ISSUE TITLE
Support per-site configuration for autoSubmit in pass entries

### ISSUE THREAD

**Issue by vaclavrak** [dannyvankooten/browserpass#251]
Hello, thank you for this nice peace of SW :) 

I have one suggestion about auto-submit. Currently is possible to have it enabled for all websites or disabled for all websites, unfortunately I found one login page with captcha and this one I could not submit before is filled in. For this reason I need to disallow autosubmit for all websites.  

my expectation is: in pass multiline option to force global extension setting I fill up line like  
```
autoSubmit: false
```

**Comment by maximbaz** [comment]
Interesting idea!

**Comment by erayd** [comment]
Stand by...
