### ISSUE TITLE
Doesn't work with symlinked password stores

### ISSUE THREAD

**Issue by eterps** [dannyvankooten/browserpass#26]
To have multiple password stores (f.i. for work and home) people tend to use symlinks for that (i.e. `.password-store -> .password-store.office`), but [go-zglob doesn't support that](https://github.com/mattn/go-zglob/issues/3). It might be better to use `pass find` instead.

**Comment by DancingQuanta** [comment]
This may get in the way of #6.

**Comment by emersion** [comment]
Note: spawning `pass` is way slower than executing Go code.

**Comment by tarciosaraiva** [comment]
Experiencing the same issue. Fixed by using `EvalSymlinks` - although would be nice to fix the issue in `go-zglob`.

Line 71 on `browserpass.go`, replace with the below:
```go
dir, _ = filepath.EvalSymlinks(os.Getenv("HOME") + "/.password-store/")
```

**Comment by tarciosaraiva** [comment]
@dannyvankooten looks like z-glob has been updated with fastwalk which, supposedly, supports symlinks. Would be keen to see the binary updated on all distros with this dependency updated.

**Comment by dannyvankooten** [comment]
Sweet, thanks for the heads up @tarciosaraiva. I'll probably be able to get to it on Monday!
