### ISSUE TITLE
Search passwords only in a specified subfolder of my password-store

### ISSUE THREAD

**Issue by mjrider** [dannyvankooten/browserpass#34]
i have a shared pass store, sync'd between me and my wife, with folders for my and here private/corporate/financial passwords

it would be awesome if i could have a settings to indicate that all filenames should start with robbert/websites/ 

example:
robbert/websites/github.com and robbert/recovery/github.com are different things, and also have different gpg keys used for encryption

**Comment by dannyvankooten** [comment]
Hey @mjrider,

Are those two separate password stores, both managed via Pass? Or is it one and the same password store, just with different directories?

If it's two different password stores then this should already be possible by making sure your the `PASSWORD_STORE_DIR` environment variable is set properly.

If not then we may be able to add support for this through an environment variable of its own.

**Comment by mjrider** [comment]
@dannyvankooten 1 store(1 git repo) 2 users

**Comment by maximbaz** [comment]
We will have a simple options page soon in https://github.com/dannyvankooten/browserpass/pull/95, this is another place where we could configure such prefix, if not with environment variable.

At the same time I'm keeping an eye on https://github.com/dannyvankooten/browserpass/issues/126, I currently also use prefixes, but I'm wondering if using several password stores with "mounts" feature from gopass is just a better way to do it.

**Comment by maximbaz** [comment]
Implemented in PR #237, will release after a few days of testing myself. Early feedback is welcome.
