### ISSUE TITLE
Passwords not loading in Firefox with GoPass

### ISSUE THREAD

**Issue by tylershuster** [dannyvankooten/browserpass#38]
First, thanks. This seems to be a great extension.

However. I have the helper installed globally and the extension in Firefox. I'm using GoPass. Here's my example: I visit accounts.google.com. In my store I have an account `web/accounts.google.com/tyler.herrshuster@gmail.com`. When I click the lock icon, that account comes up. Nice. I click the account name and the spinner starts doing its thing. No console output (in the standard FF console, not sure if there's another one I can check). 

Do you know why this might be happening? What should I check next?

**Comment by emersion** [comment]
Please check the browser console.

**Comment by tylershuster** [comment]
Nothing

**Comment by tylershuster** [comment]
Looks like this is the same problem as #28
