### ISSUE TITLE
Browserpass doesn't shutdown nicely

### ISSUE THREAD

**Issue by Timvde** [dannyvankooten/browserpass#39]
I just had this crash: https://crash-stats.mozilla.com/report/index/559fd09d-e3dc-4990-b061-0df062170209

I'm not sure whether it is a bug in browserpass or in Firefox, but I wanted to mention, at least.

**Comment by dannyvankooten** [comment]
Hi @Timvde,

Thanks for shooting in an issue. I'm not sure whether it's Browserpass responsible for this. The browser add-on uses `chrome.runtime.sendNativeMessage` which should invoke the binary and then immediately shuts it down. Will keep an eye on this though.

**Comment by maximbaz** [comment]
I'll close this for cleanup purposes since it doesn't seem to be actionable on our side, and it hasn't repeated for more than half a year now.

Feel free to reopen if this becomes an issue again.
