### ISSUE TITLE
32bit?

### ISSUE THREAD

**Issue by carks32** [dannyvankooten/browserpass#42]
Just wanna know if it's possible to make it 32bit compatible.

**Comment by emersion** [comment]
Normally that's just a matter of changing build flags in https://github.com/dannyvankooten/browserpass/blob/master/makefile#L26

**Comment by maximbaz** [comment]
To answer the question: yes, it is possible, as was suggested above. 

However, I don't see a point in keeping this request open, especially as nobody :+1: it as of today. We have nowhere to even test the binary 🙂 

So, I'll close this issue for cleanup purposes, and if someone needs this, please create a PR.
