### ISSUE TITLE
Uncaught TypeError - Not working with login box inside embedded frame.

### ISSUE THREAD

**Issue by Adam-Ant** [dannyvankooten/browserpass#46]
Browser pass is not working with twitch.tv, returning a `Uncaught TypeError: Cannot read property 'form' of null`. Looking at the Chrome Developer window, it is extracting the password from Pass. I suspect this has something todo with Twitch not having the login form on the page, instead loading a frame of https://passport.twitch.tv/authentications/.

**Comment by maximbaz** [comment]
Hey @Adam-Ant, I've stumbled on the same issue myself, and made a PR #55 to attempt to fix it. This does fix my case, if you have a chance to test it for your website, please do and let me know how it goes.
