### ISSUE TITLE
Opera: Can't find manifest for native messaging host com.dannyvankooten.browserpass

### ISSUE THREAD

**Issue by zamber** [dannyvankooten/browserpass#47]
Installed from the [Chrome extension store](https://chrome.google.com/webstore/detail/browserpass/jegbgfamcgeocbfeebacnkociplhmfbk/related) on Opera 43.0.2442.806 (via [enable chrome extensions](https://addons.opera.com/pl/extensions/details/download-chrome-extension-9/?display=en)).

Similar to #8. I've got passwords structured as `domain.com/username`. Password-store is installed from the official Ubuntu 16.04 repo. Version 1.6.5.

I'm getting `"Specified native messaging host not found."`. Bugs out on line 101 in the `chrome.runtime.lastError` if clause.

Also there's `Unchecked runtime.lastError while running browserAction.setIcon: Icon invalid.` but that's probably not important.

...

Launched Opera from the command line and got:

    [0306/121323.276268:ERROR:native_process_launcher.cc(130)] Can't find manifest for native messaging host com.dannyvankooten.browserpass

Also found a [similar thread on the Opera Dev forums](http://forums.opera.com/discussion/1873500/porting-extension-from-chrome-macos-native-messaging/p1).

**Comment by dannyvankooten** [comment]
Hey @zamber,

Right now there is no support for Opera in the install.sh script as it does not yet know where to copy the manifest file, which is what the error message you see is about.

The thread you link to lists the following file locations:

- On Linux: ~/.config/opera-developer/NativeMessagingHosts/com.mycompany.myapplication.json
- On OSX (I guess): ~/Library/Application Support/Opera/NativeMessagingHosts/com.mycompany.myapplication.json

Knowing this, it should be fairly easy to modify the [install.sh](https://github.com/dannyvankooten/browserpass/blob/master/install.sh) file to add support for Opera too. For a quick test, you could try running the install script for a different browser and then copying the generated file to the correct location.

**Comment by zamber** [comment]
Ah, ok. Problem solved. I failed to read the installation instructions correctly, IMHO this should be handled in the extension with a more verbose error information (missing manifest and/or missing binary, link to the installation instructions).

As a side note, installing the binary for Chrome works perfectly fine for Opera :).

**Comment by maximbaz** [comment]
Good to know that selecting Chrome works for Opera, I guess it's because you install browserpass as Chrome extension 🙂

I've just fixed the support for Aliexpress login form in https://github.com/dannyvankooten/browserpass/commit/82e69b5be4c5192e87c186d1be312671570e2308

Closing this issue now, if you find any new ones - please open new tickets.
