### ISSUE TITLE
Fix EOF errors returned by host

### ISSUE THREAD

**Issue by dannyvankooten** [dannyvankooten/browserpass#48]
```
stderr output from native app com.dannyvankooten.browserpass: [Browserpass] 2017/03/10 14:07:41 EOF
```

Introduced by 2ebdd5a388be431882f702e3ed788f385ebd4eaf, I believe.

**Comment by emersion** [comment]
Will look into this issue. I think this happens when the browser closes stdin, which makes a `Read` call return `io.EOF`.
