### ISSUE TITLE
Missing svg for key and search

### ISSUE THREAD

**Issue by seanfarley** [dannyvankooten/browserpass#67]
I was about to make a PR for increasing the resolution for the icons since they're blurry on retina / hidpi screens but couldn't find the svgs for the key or search icon.

**Comment by maximbaz** [comment]
You know what's still blurry? The "lock" icon 🙂 

![image](https://cloud.githubusercontent.com/assets/1177900/26002231/51010eaa-372f-11e7-935f-ba4426c2b327.png)

**Comment by dannyvankooten** [comment]
The [browser manifest file doesn't allow for .svg icons](https://bugs.chromium.org/p/chromium/issues/detail?id=29683) but [we're setting the SVG icon in the actual extension script](https://github.com/dannyvankooten/browserpass/blob/master/chrome/script.browserify.js#L13). Either that isn't working or I just picked a shitty SVG.

**Comment by maximbaz** [comment]
SVG file is all right by itself, it's a pity that it is not directly supported at the moment.

I don't think that code is doing anything, but we could at least increase the resolution of the png icon while waiting for the real support of SVG format. This leads to PR #75 🙂
