### ISSUE TITLE
Shortcut does not open popup on Mac

### ISSUE THREAD

**Issue by mcnesium** [dannyvankooten/browserpass#72]
In Firefox 53.0 (64-Bit) / Mac the shortcut to open up the browserpass popup only works when starting Firefox from the command line using `open -a firefox`.

This might be related to #19

**Comment by dannyvankooten** [comment]
Yes, most likely it is. Where are you setting the `pass` environment variables or are you using the defaults?

**Comment by mcnesium** [comment]
I am using the defaults, I guess.

**Comment by maximbaz** [comment]
This looks like #13, the reason being environment variables that are not propagated to GUI apps on Mac unless started from terminal. There is a workaround posted which you can try.

If this happens to be a different issue after all, please reopen the issue.
