### ISSUE TITLE
Permission changes

### ISSUE THREAD

**Issue by bennyty** [dannyvankooten/browserpass#76]
Why did the permissions for browserpass change? They seem reasonable to me but why were these not the permissions when I installed the extension?

[http://i.imgur.com/gvFt0mQ.png](http://i.imgur.com/gvFt0mQ.png)

**Comment by maximbaz** [comment]
The reason is to support websites, whose login form is located in the iframe. Unfortunately there is no other way to enumerate iframes, but to request higher permissions.

See https://github.com/dannyvankooten/browserpass/pull/55 for the details.
