### ISSUE TITLE
unable to install on Mac

### ISSUE THREAD

**Issue by siwan05** [dannyvankooten/browserpass#80]
Hey guys,
I'm trying to get this running in Chrome on my Mac. I simply installed the extension, downloaded the package browserpass-darwinx64 and when trying to execute the install script I first get to select my browser and then I get the following error:
"
Installing Chrome host config
cp: /X/files/browserpass-darwinx64/chrome-policy.json: No such file or directory
"
From what I can see that file is not part of the package, have I missed some step that I should have done before running the install script?

Cheers,
siwan

**Comment by dannyvankooten** [comment]
Hey @siwan05,

You're right, looks like the make target is broken for building the release package, the `chrome-policy.json` file should be there but is missing.

**Comment by benni336** [comment]
So what does it mean now. I wanted to install it with vivaldi. This leads to the same bug. Any shortcut/workaround?

**Comment by benni336** [comment]
blame me for stupidity :(
Everything is ok for installation. Just use one of the release versions here:
https://github.com/dannyvankooten/browserpass/releases/

**Comment by jeffutter** [comment]
I'm using a release version (1.0.4) and get this error for Chrome on MacOS.

**Comment by dgrusemann** [comment]
I am also getting that error using the latest release version (1.0.6).
Was able to fix the error by using and renaming the file from the source package.

**Comment by compuguy** [comment]
@dgrusemann I'm guessing you just renamed the chrome-host.json file to chrome-policy.json?

**Comment by rafi** [comment]
I solved this with `mv policy.json chrome-policy.json`

**Comment by dgrusemann** [comment]
Yes, it was done using the solution @rafi mentioned.

**Comment by juanibiapina** [comment]
Release 1.0.6 also doesn't work with same error.

**Comment by inferiorhumanorgans** [comment]
@rafi's fix doesn't work for me as there's no policy.json in 1.0.6.

**Comment by maximbaz** [comment]
This has been fixed in `master` thanks to #114.
