### ISSUE TITLE
Unable to find passwords on URLs with sub-domain

### ISSUE THREAD

**Issue by pbrisbin** [dannyvankooten/browserpass#81]
Expected:

When I'm on the page "manage.statuspage.io", the extension should find my password stored at `manage.statuspage.io/...`

Actual:

The extension appears to search for "statuspage.io" (which does work with `pass find`), and finds no results.

Steps to reproduce:

1. Store a password for `subdomain.something.com/username`
1. Visit `subdomain.something.com`
1. Use the extension

Details:

![browserpass](https://cloud.githubusercontent.com/assets/50812/26264805/1db2ec9e-3cac-11e7-9fe2-a7b6f8bc74a5.png)

This has been happening since the most recent update, the one that requested more permissions. Before then, this was working great. Passwords for URLs without a sub-domain (e.g. `github.com/pbrisbin`) are working fine.

I didn't fully understand the logic of when the extension ignored sub-domains or not, but however it worked previously felt right and whatever it's doing now has drastically increased the miss rate for me. As a naive developer I would expect the extension to delegate fully to `pass find {current url}`, which works consistently.

**Comment by speze88** [comment]
I'm seeing the same behavior since the last update. Was this intentionally changed?

**Comment by Miterion** [comment]
Made a pull request fixing this issue #82

**Comment by pbrisbin** [comment]
Thanks @Miterion! I've installed from your branch and can confirm it fixes this bug. I'll keep using it and report any unexpected regressions.

**Comment by dannyvankooten** [comment]
Great catch @Miterion, thanks for submitting a PR!

**Comment by Fraterius** [comment]
I've just downloaded latest version for chrome, which installs as v1.0.5 and doesn't work with subdomains (www for example).
