### ISSUE TITLE
Browserpass does not follow symlinks to directories inside password store

### ISSUE THREAD

**Issue by JanKoppe** [dannyvankooten/browserpass#85]
Hi,
I've got separate project-based password-stores in my filesystem, to which I symlink from my main password-store. Using the cli this works acceptably, but the browserpass extension does not find matches in those linked directories, doing a direct search (even typing out the complete path) does not resolve to the linked passwords.
Would it be possible to fix that?

**Comment by maximbaz** [comment]
Hey @JanKoppe, I've seen this being fixed back in January (see #26), and I've actually tried now - things seem to work just for me with symlinks.

Is this still an issue for you, or it can be closed?

**Comment by JanKoppe** [comment]
Yes, this still does not work for me.

Setup:
Arch Linux
Pass v1.7.1
browserpass 1.0.6

Regular pass-store in `~/.password-store`, linked passwordstore with `ln -s ~/git/some/other/store ~/.password-store/subdir/otherstore`. Subdir existed previously of course.  Browserpass will not find passwords in the symlinked store, even if I type out the entire path or portions of it in the search field.

On the other hand, if I include the other store as a git submodule inside my personal store everything works just fine (which is to be expected, because then they are just regular files).

**Comment by maximbaz** [comment]
Ah I see, what I was trying is a case when you have `.password-store-1` and `.password-store-2` directories, and a symlink `.password-store` exists which is entirely pointing to one of the two folders - but what you describe is a symlink _inside_ the `.password-store`. Valid issue then, thanks for explanation.

You might also be interested to follow #77 where we discuss supporting "mounts" feature from gopass, which sounds like something very close to what you are doing.

**Comment by JanKoppe** [comment]
Sorry, I have worded the original issue badly then. That is exactly what I mean. We're all using the original pass at work, not sure if gopass mounts are applicable for us. I think supporting symlinks inside the password-store would be the most flexible option.

**Comment by maximbaz** [comment]
Investigated a little bit, this is what will get this bug fixed: https://github.com/mattn/go-zglob/issues/11

**Comment by maximbaz** [comment]
Good news, this is implemented now. 

This enables another useful use-case, now you can share multiple accounts between domains.

For example, this is how your `.password-store` structure might look like:

```
.password-store/
   amazon.com/
      user1.gpg
      user2.gpg
   amazon.co.uk -> amazon.com
```

**Comment by JanKoppe** [comment]
Very nice, will have to try it with the next release. Thank you very much for your work put into this!
