### ISSUE TITLE
Only autofills in after clicking 'Inspect Object' in developer mode

### ISSUE THREAD

**Issue by lobachevzky** [dannyvankooten/browserpass#86]
The title says it all. I made a quick screencast and posted on youtube so you can see what I'm talking about:
https://www.youtube.com/watch?v=ToXt9nHovO8&feature=em-upload_owner

**Comment by jayme-github** [comment]
This is a duplicate of #83 (#87).

**Comment by lobachevzky** [comment]
Can you explain what those issues have to do with clicking 'Inspect Object'?

**Comment by maximbaz** [comment]
When pinentry dialog opens, the browserpass popup gets closed. When it is closed, it is destroyed - it will not receive your password and will not fill it on the website. This is how chrome extension popups are designed, and there is nothing we can do about it.

However, when you "Inspect popup", the developer panel keeps the popup alive, and so even though pientry dialog was opened, the popup is still there and it still receives the password and is able to fill it on the page.

See #83, there were some links posted that explain this behavior.

**Comment by lobachevzky** [comment]
I see. Thank you.
