### ISSUE TITLE
Form not filled when gpg asks for a password

### ISSUE THREAD

**Issue by jayme-github** [dannyvankooten/browserpass#87]
OS Linux
pass 1.7.1
browserpass 1.0.4
chrome 58

If gpg prompts for my passphrase when selecting a password from browserpass, the username/password is not filled after entering the gpg passphrase.
I need to re-select the password in browserpass to have the login form filled correctly (with gpg passphrase in gpg-agent's cache).

**Comment by jayme-github** [comment]
Autofill always works when inspect popup is open (#86)

**Comment by maximbaz** [comment]
Also possibly related: #83

**Comment by jayme-github** [comment]
Closing in favor of #83 as it has more history and details.
