### ISSUE TITLE
Fedora 25: automatic search for passwords works on Firefox but not on chrome/chromium

### ISSUE THREAD

**Issue by NeoFromMatrix** [dannyvankooten/browserpass#88]
Just installed passwordstore and browserpass plugin in the browsers. Installed browserpass access via the install.sh script for all three browsers.

Passwordstore setup for one domain with multiple passwords is e.g.:
/home/$USER/.password-store/reddit.com/username1.gpg
/home/$USER/.password-store/reddit.com/username2.gpg

In Firefox it shows the suggestions for reddit.com automatically when I am at that domain and click on the app icon.
But only a "Not passwords found for www.reddit.com" on chrome and chromium. When I type the domain (reddit.com) into the search field of the app and confirm with enter, the search starts and lists the passwords. 
But this search is not started automatically as it seams.

**Comment by NeoFromMatrix** [comment]
Browserpass:
browserpass-linux64.zip -> v1.0.5

OS:
Fedora 25 XFCE

Browsers:
Firefox 53.0.3 (64-bit)
Google Chrome 58.0.3029.110 (64-bit)
Chromium 58.0.3029.110 Fedora Project (64-bit)

**Comment by dannyvankooten** [comment]
This was most likely due to the same build error as #90 and #91. Downloading the latest host binary application from the [most recent release](https://github.com/dannyvankooten/browserpass/releases) should fix it! :tada:
