### ISSUE TITLE
New pass version v1.0.5 does not find passwords in store

### ISSUE THREAD

**Issue by tanderson92** [dannyvankooten/browserpass#90]
I am on chromium 55.0.2883.87, with the new pass v1.0.5. When I use the shortcut on, say, https://www.bankofamerica.com/ , browserpass now returns  "no passwords found for ...". This did not occur with the previous browserpass version.

**Comment by jirka-grunt** [comment]
Same here. When I have password saved as `example.com/username` new Chromium finds password for `example.com` but not for `www.example.com`. Saving as `www.example.com/username` works for Chromium, but it doesn't work for `www.example.com` in Firefox.

**Comment by maximbaz** [comment]
@dannyvankooten, @Thor77 there were a few commits recently reworking domains parsing, the automatic search is in a very broken state now. This issue, as well as #88 and #91 are all because of that. If the solution is not immediately clear, could you please consider reverting and making another attempt afterwards?

**Comment by maximbaz** [comment]
@Miterion, @Thor77: there were only two your PRs since v1.0.4, that's why I /cc you - maybe you'll have some insights 🙂

**Comment by dannyvankooten** [comment]
Could very well be that the way the domain is parsed always adds `www.`, which we used to strip in earlier versions. But with the recursive subdomain search added in #84, this should not really be an issue.

@maximbaz @jirka-grunt  did you update the host binary application? The browser extension should update automatically, but you may have to update the host binary manually by downloading it from the latest release.

**Comment by maximbaz** [comment]
Just double checked, I have v1.0.5 installed from [AUR](https://aur.archlinux.org/packages/browserpass).

**Comment by jirka-grunt** [comment]
yes, my `browserpass-linux64` is up to date (md5 `9a7fc3df4be7a37f083b50b130df022f`), browser extension 1.0.5

**Comment by Thor77** [comment]
Can't reproduce in Firefox (55.0a1) and Chrome (59.0.3071.86) on ArchLinux.

**Comment by Thor77** [comment]
Oh, can reproduce with binary from releases, though.
Seems like there is an issue with the provided binary releases @dannyvankooten

**Comment by dannyvankooten** [comment]
The make task is only watching files in the `cmd/browserpass` package, therefore not building the updated binaries. On it as we speak. :)

**Comment by dannyvankooten** [comment]
Downloading the latest host binary application from the [most recent release](https://github.com/dannyvankooten/browserpass/releases) should fix it. :tada: Thanks for the heads up & help everyone!

**Comment by maximbaz** [comment]
Fix confirmed, thanks 🙂

**Comment by tanderson92** [comment]
Thanks everyone. I also saw #84 which looks fantastic. Waiting for the chrome store to get the update before happy sailing. 

Great tool, thanks for all the efforts.
