### ISSUE TITLE
no password found

### ISSUE THREAD

**Issue by nerdDan** [dannyvankooten/browserpass#91]
Arch Linux.
`pass` works perfectly in terminal.
`browserpass` installed from AUR.

Chrome extension does not find a single password.

![screenshot from 2017-06-15 18-49-13](https://user-images.githubusercontent.com/3108734/27178290-465f1324-51fc-11e7-8211-babd1c1d5267.png)

**Comment by dannyvankooten** [comment]
This was most likely due to a build error in the previous release. Downloading the latest host binary application from the [most recent release](https://github.com/dannyvankooten/browserpass/releases) should fix it! :tada:
