### ISSUE TITLE
autofill without submit

### ISSUE THREAD

**Issue by jceloria** [dannyvankooten/browserpass#94]
AWS IAM logins use input_account, input_username and input_password, the username replaces the account number and submits the form without the username (see attached images)

![screen shot 2017-06-16 at 9 22 52 am](https://user-images.githubusercontent.com/1354592/27232124-75ce21e4-527a-11e7-8e97-1fb0354be9d0.png)
![screen shot 2017-06-16 at 9 23 38 am](https://user-images.githubusercontent.com/1354592/27232126-7825e8f0-527a-11e7-9703-418141dd2c06.png)

It would be helpful to provide the option to fill without submitting.

**Comment by maximbaz** [comment]
Same applies when there's a checkbox "Remember me", after filling the credentials the form is submitted without having a chance to tick the checkbox. 

I'd also prefer to entirely disable automatic form submission.

**Comment by compuguy** [comment]
Have the same issue with Amazon IAM. It would be nice if it just didn't touch the input_account and filled the login under input_username.

**Comment by compuguy** [comment]
Related: #101

**Comment by maximbaz** [comment]
Fixed in master.
