### ISSUE TITLE
Light Icon for Dark Themes

### ISSUE THREAD

**Issue by ainola** [dannyvankooten/browserpass#96]
Thanks for this great extension!

When using a dark theme, the lock tends to hide itself.

![screenshot at 2017-06-20 20-47-38](https://user-images.githubusercontent.com/5383525/27364808-f8988484-55f9-11e7-8982-a4821241ac3f.png)

**Comment by maximbaz** [comment]
I couldn't find a way to detect the browser color scheme, thus introducing a cheap fix - one icon that looks good on both Light and Dark themes:

Chrome Light:

![image](https://user-images.githubusercontent.com/1177900/31047081-64684744-a604-11e7-94ba-15894bb1c070.png)

Chrome Dark:

![image](https://user-images.githubusercontent.com/1177900/31047083-716f2eb2-a604-11e7-82e5-2f428b5a6726.png)

Firefox Dark:

![image](https://user-images.githubusercontent.com/1177900/31047085-78f94b72-a604-11e7-8b43-6da68e5ac5e3.png)

**Comment by Thor77** [comment]
Uh, I don't like the new, blue, icon at all, to be honest, it's very distracting and you can't look at your topbar without noticing it.
Maybe try using a darker blue or a more pale color?

**Comment by maximbaz** [comment]
I experimented with tones of colors while expecting the current one, choose darker and it looks bad on the dark theme... But I'm open for suggestions :)

If you want to experiment, take a screenshot of my previous post with 3 browsers, choose a color and just paint over the lock icon with the new color, and when you like the result, give me the #hex of the color and I'll try it as well :)

**Comment by Thor77** [comment]
I chose a slightly more pale tone and I think it looks less distracting:

![browserpass_screenshot](https://user-images.githubusercontent.com/4989736/31054414-6316cfd8-a6b2-11e7-81a1-5921686dc3ae.png)

Hex: `#5f8dd3`

If you happen to like this suggestion, I'm happy to create a PR as I already edited the according .svg-file on my (local) branch.

**Comment by maximbaz** [comment]
I like it 🙂 Especially on the dark theme it looks even nicer. I'll generate PNGs and commit myself, no worries - thanks for the contribution :+1: 

For reference:

Chrome Light:

![image](https://user-images.githubusercontent.com/1177900/31054483-d34b71f4-a6b3-11e7-995e-70a9f1cc0f4b.png)

Chrome Dark:

![image](https://user-images.githubusercontent.com/1177900/31054485-dfbf0aae-a6b3-11e7-8054-4e55253708d3.png)

Firefox Dark (before and after):

![image](https://user-images.githubusercontent.com/1177900/31047085-78f94b72-a604-11e7-8b43-6da68e5ac5e3.png)

![image](https://user-images.githubusercontent.com/1177900/31054466-77f0cde0-a6b3-11e7-8850-bb1c9269e524.png)
