### ISSUE TITLE
Extension is disabled in Chrome app mode

### ISSUE THREAD

**Issue by aconthea** [dannyvankooten/browserpass#97]
Hi, I am using Chrome on Linux with configuration to open several urls in app mode using `google-chrome --app=<url>`

Now i am not sure if there is a limitation with Chrome or the extension itself has an issue but I can not use this extension in app mode. Pressing the shortcut key does nothing. Did some research online, but could not find anything helpful. I have some other extensions that I can use in app mode (namely cVim).

Any idea about this issue ?

**Comment by maximbaz** [comment]
I can reproduce this, looks like Chrome doesn't support extensions that launch via commands.

https://github.com/dannyvankooten/browserpass/blob/82e69b5be4c5192e87c186d1be312671570e2308/chrome/manifest.json#L32-L37

I found two valuable pieces of information:
- You are definitely not the only one asking, here is [another unsolved question](https://askubuntu.com/questions/850216/what-command-to-use-to-start-chrome-with-extensions-on) about extensions in app mode.
- Using `google-chrome --kiosk <url>` opens the same borderless window, but there extensions work! The only difference I found is that the window starts in full screen, but at least in i3 I can easily exit the full screen mode.

I'm afraid there is nothing we could do on our side to solve the issue. I suggest you to either use `--kiosk` mode or submit a [bug report for Chromium](https://bugs.chromium.org/p/chromium/issues/list).

**Comment by aconthea** [comment]
Thanks @maximbaz I will submit a bug report I think. Kiosk does not really work if you have a chrome running in the background, or a chrome instance is already running. 

It seems to work only if you start Chrome the first in kioks mode it seems to work. Which makes sense as the names suggest it is for kiosks.

**Comment by florianrusch** [comment]
@breneser can you provide a link to the bug report?

**Comment by florianrusch** [comment]
Never mind...I found a solution. You have to add `--enable-extensions` also to the startup command.

e.g.: `google-chrome --app=<url> --enable-extensions`

**Comment by maximbaz** [comment]
Nice finding!

**Comment by lsim** [comment]
On windows with chrome 73, I can get app mode in the presence of existing chrome windows complete with extensions running with something as simple as the following:

`chrome.exe --app=https://duckduckgo.com --new-window`

Without `--new-window`, the `--app` argument is ignored if there is a running instance of chrome already.
