### ISSUE TITLE
Option to specify password store directory

### ISSUE THREAD

**Issue by e-user** [dannyvankooten/browserpass#98]
Currently, browserpass aligns with `pass` on the commandline by reading the environment variable `PASSWORD_STORE_DIR` to determine the directory to obtain passwords from.  
However, at least Chromium and Chrome are designed to switch users and contexts within the same instance of the browser, which means these contexts can't use different password stores. On the commandline, the environment variable can simply be set and unset, but for the browser, that's not possible. 

Presumably the most typical use case for this is to have a browser window for work and one for private matters, each using a different Chromium "user". 

Please add a feature to specify the password store directory as an add-on option, so different browser contexts can use different password stores.

**Comment by rafi** [comment]
I also set my `$PASSWORD_STORE_DIR` to somewhere else, had to create a symlink to `~/.password-store`..  It would be awesome if there was an option for this.

**Comment by maximbaz** [comment]
As a workaround, you could try creating different desktop shortcuts for different Chrome user profiles, and then editing them and changing their executable from let's say `chrome` to `PASSWORD_STORE_DIR=/home/user/.password-store chrome` - not sure if it will work, but worth a try.

#77 might also be related depending on how it gets implemented.

**Comment by zsau** [comment]
Any thoughts on this? It would be awesome if we could set different store dirs per [container](https://support.mozilla.org/en-US/kb/containers), though I'm not sure what the official status of containers is right now.

**Comment by maximbaz** [comment]
I'm kind of hoping to see #77 implemented one day in a way that is not really dependent on gopass, but instead just a configurable list in the options window allowing users to define different password store dirs. That way it would solve this request, #77 and #34 in one go.

**Comment by maximbaz** [comment]
Implemented in PR #237, will release after a few days of testing myself. Early feedback is welcome.
